call sqlhydra-mssql-net7.bat
call sqlhydra-mssql-net8.bat
call sqlhydra-mssql-net9.bat
call sqlhydra-npgsql-net7.bat
call sqlhydra-npgsql-net8.bat
call sqlhydra-npgsql-net9.bat
call sqlhydra-oracle-net7.bat
call sqlhydra-oracle-net8.bat
call sqlhydra-oracle-net9.bat
call sqlhydra-sqlite-net7.bat
call sqlhydra-sqlite-net8.bat
call sqlhydra-sqlite-net9.bat
