// This code was generated by `SqlHydra.Sqlite` -- v4.1.0-beta.2.
namespace Sqlite.AdventureWorksNet8

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 1, 0)
    let ns = "Sqlite.AdventureWorksNet8"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    [<CLIMutable>]
    type Address =
        { AddressID: int64
          AddressLine1: Sqlite.CustomTypes.Text
          AddressLine2: Option<Sqlite.CustomTypes.Text>
          City: Sqlite.CustomTypes.Text
          StateProvince: Sqlite.CustomTypes.Text
          CountryRegion: Sqlite.CustomTypes.Text
          PostalCode: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

    let Address = table<Address>

    [<CLIMutable>]
    type BuildVersion =
        { SystemInformationID: int64
          ``Database Version``: Sqlite.CustomTypes.Text
          VersionDate: System.DateTime
          ModifiedDate: System.DateTime }

    let BuildVersion = table<BuildVersion>

    [<CLIMutable>]
    type Customer =
        { CustomerID: int64
          NameStyle: int64
          Title: Option<Sqlite.CustomTypes.Text>
          FirstName: Sqlite.CustomTypes.Text
          MiddleName: Option<Sqlite.CustomTypes.Text>
          LastName: Sqlite.CustomTypes.Text
          Suffix: Option<Sqlite.CustomTypes.Text>
          CompanyName: Option<Sqlite.CustomTypes.Text>
          SalesPerson: Option<Sqlite.CustomTypes.Text>
          EmailAddress: Option<Sqlite.CustomTypes.Text>
          Phone: Option<Sqlite.CustomTypes.Text>
          PasswordHash: Sqlite.CustomTypes.Text
          PasswordSalt: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

    let Customer = table<Customer>

    [<CLIMutable>]
    type CustomerAddress =
        { CustomerID: int64
          AddressID: int64
          AddressType: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

    let CustomerAddress = table<CustomerAddress>

    [<CLIMutable>]
    type ErrorLog =
        { ErrorLogID: int64
          ErrorTime: System.DateTime
          UserName: Sqlite.CustomTypes.Text
          ErrorNumber: int64
          ErrorSeverity: Option<int64>
          ErrorState: Option<int64>
          ErrorProcedure: Option<Sqlite.CustomTypes.Text>
          ErrorLine: Option<int64>
          ErrorMessage: Sqlite.CustomTypes.Text }

    let ErrorLog = table<ErrorLog>

    [<CLIMutable>]
    type Product =
        { ProductID: int64
          Name: Sqlite.CustomTypes.Text
          ProductNumber: Sqlite.CustomTypes.Text
          Color: Option<Sqlite.CustomTypes.Text>
          StandardCost: int64
          ListPrice: int64
          Size: Option<Sqlite.CustomTypes.Text>
          Weight: Option<int64>
          ProductCategoryID: Option<int64>
          ProductModelID: Option<int64>
          SellStartDate: System.DateTime
          SellEndDate: Option<System.DateTime>
          DiscontinuedDate: Option<System.DateTime>
          ThumbNailPhoto: Option<byte[]>
          ThumbnailPhotoFileName: Option<Sqlite.CustomTypes.Text>
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

    let Product = table<Product>

    [<CLIMutable>]
    type ProductCategory =
        { ProductCategoryID: int64
          ParentProductCategoryID: Option<int64>
          Name: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

    let ProductCategory = table<ProductCategory>

    [<CLIMutable>]
    type ProductDescription =
        { ProductDescriptionID: int64
          Description: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

    let ProductDescription = table<ProductDescription>

    [<CLIMutable>]
    type ProductModel =
        { ProductModelID: int64
          Name: Sqlite.CustomTypes.Text
          CatalogDescription: Option<Sqlite.CustomTypes.Text>
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

    let ProductModel = table<ProductModel>

    [<CLIMutable>]
    type ProductModelProductDescription =
        { ProductModelID: int64
          ProductDescriptionID: int64
          Culture: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

    let ProductModelProductDescription = table<ProductModelProductDescription>

    [<CLIMutable>]
    type SalesOrderDetail =
        { SalesOrderID: int64
          SalesOrderDetailID: int64
          OrderQty: int64
          ProductID: int64
          UnitPrice: int64
          UnitPriceDiscount: int64
          LineTotal: int64
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

    let SalesOrderDetail = table<SalesOrderDetail>

    [<CLIMutable>]
    type SalesOrderHeader =
        { SalesOrderID: int64
          RevisionNumber: int64
          OrderDate: System.DateTime
          DueDate: System.DateTime
          ShipDate: Option<System.DateTime>
          Status: int64
          OnlineOrderFlag: int64
          SalesOrderNumber: string
          PurchaseOrderNumber: Option<int64>
          AccountNumber: Option<Sqlite.CustomTypes.Text>
          CustomerID: int64
          ShipToAddressID: Option<int>
          BillToAddressID: Option<int>
          ShipMethod: Sqlite.CustomTypes.Text
          CreditCardApprovalCode: Option<Sqlite.CustomTypes.Text>
          SubTotal: int64
          TaxAmt: int64
          Freight: int64
          TotalDue: int64
          Comment: Option<Sqlite.CustomTypes.Text>
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

    let SalesOrderHeader = table<SalesOrderHeader>



type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqliteEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
