// This code was generated by `SqlHydra.Sqlite` -- v4.1.0.
namespace Sqlite.AdventureWorksNet8

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 1, 0)
    let ns = "Sqlite.AdventureWorksNet8"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    [<CLIMutable>]
    type Address =
        { AddressID: int64
          AddressLine1: Sqlite.CustomTypes.Text
          AddressLine2: Option<Sqlite.CustomTypes.Text>
          City: Sqlite.CustomTypes.Text
          StateProvince: Sqlite.CustomTypes.Text
          CountryRegion: Sqlite.CustomTypes.Text
          PostalCode: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "AddressID"
                    Value = box this.AddressID
                    ProviderDbType = None }
                  { WriteColumn.Name = "AddressLine1"
                    Value = box this.AddressLine1
                    ProviderDbType = None }
                  { WriteColumn.Name = "AddressLine2"
                    Value = box this.AddressLine2
                    ProviderDbType = None }
                  { WriteColumn.Name = "City"
                    Value = box this.City
                    ProviderDbType = None }
                  { WriteColumn.Name = "StateProvince"
                    Value = box this.StateProvince
                    ProviderDbType = None }
                  { WriteColumn.Name = "CountryRegion"
                    Value = box this.CountryRegion
                    ProviderDbType = None }
                  { WriteColumn.Name = "PostalCode"
                    Value = box this.PostalCode
                    ProviderDbType = None }
                  { WriteColumn.Name = "rowguid"
                    Value = box this.rowguid
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let Address = table<Address>

    [<CLIMutable>]
    type BuildVersion =
        { SystemInformationID: int64
          ``Database Version``: Sqlite.CustomTypes.Text
          VersionDate: System.DateTime
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "SystemInformationID"
                    Value = box this.SystemInformationID
                    ProviderDbType = None }
                  { WriteColumn.Name = "Database Version"
                    Value = box this.``Database Version``
                    ProviderDbType = None }
                  { WriteColumn.Name = "VersionDate"
                    Value = box this.VersionDate
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let BuildVersion = table<BuildVersion>

    [<CLIMutable>]
    type Customer =
        { CustomerID: int64
          NameStyle: int64
          Title: Option<Sqlite.CustomTypes.Text>
          FirstName: Sqlite.CustomTypes.Text
          MiddleName: Option<Sqlite.CustomTypes.Text>
          LastName: Sqlite.CustomTypes.Text
          Suffix: Option<Sqlite.CustomTypes.Text>
          CompanyName: Option<Sqlite.CustomTypes.Text>
          SalesPerson: Option<Sqlite.CustomTypes.Text>
          EmailAddress: Option<Sqlite.CustomTypes.Text>
          Phone: Option<Sqlite.CustomTypes.Text>
          PasswordHash: Sqlite.CustomTypes.Text
          PasswordSalt: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "CustomerID"
                    Value = box this.CustomerID
                    ProviderDbType = None }
                  { WriteColumn.Name = "NameStyle"
                    Value = box this.NameStyle
                    ProviderDbType = None }
                  { WriteColumn.Name = "Title"
                    Value = box this.Title
                    ProviderDbType = None }
                  { WriteColumn.Name = "FirstName"
                    Value = box this.FirstName
                    ProviderDbType = None }
                  { WriteColumn.Name = "MiddleName"
                    Value = box this.MiddleName
                    ProviderDbType = None }
                  { WriteColumn.Name = "LastName"
                    Value = box this.LastName
                    ProviderDbType = None }
                  { WriteColumn.Name = "Suffix"
                    Value = box this.Suffix
                    ProviderDbType = None }
                  { WriteColumn.Name = "CompanyName"
                    Value = box this.CompanyName
                    ProviderDbType = None }
                  { WriteColumn.Name = "SalesPerson"
                    Value = box this.SalesPerson
                    ProviderDbType = None }
                  { WriteColumn.Name = "EmailAddress"
                    Value = box this.EmailAddress
                    ProviderDbType = None }
                  { WriteColumn.Name = "Phone"
                    Value = box this.Phone
                    ProviderDbType = None }
                  { WriteColumn.Name = "PasswordHash"
                    Value = box this.PasswordHash
                    ProviderDbType = None }
                  { WriteColumn.Name = "PasswordSalt"
                    Value = box this.PasswordSalt
                    ProviderDbType = None }
                  { WriteColumn.Name = "rowguid"
                    Value = box this.rowguid
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let Customer = table<Customer>

    [<CLIMutable>]
    type CustomerAddress =
        { CustomerID: int64
          AddressID: int64
          AddressType: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "CustomerID"
                    Value = box this.CustomerID
                    ProviderDbType = None }
                  { WriteColumn.Name = "AddressID"
                    Value = box this.AddressID
                    ProviderDbType = None }
                  { WriteColumn.Name = "AddressType"
                    Value = box this.AddressType
                    ProviderDbType = None }
                  { WriteColumn.Name = "rowguid"
                    Value = box this.rowguid
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let CustomerAddress = table<CustomerAddress>

    [<CLIMutable>]
    type ErrorLog =
        { ErrorLogID: int64
          ErrorTime: System.DateTime
          UserName: Sqlite.CustomTypes.Text
          ErrorNumber: int64
          ErrorSeverity: Option<int64>
          ErrorState: Option<int64>
          ErrorProcedure: Option<Sqlite.CustomTypes.Text>
          ErrorLine: Option<int64>
          ErrorMessage: Sqlite.CustomTypes.Text }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ErrorLogID"
                    Value = box this.ErrorLogID
                    ProviderDbType = None }
                  { WriteColumn.Name = "ErrorTime"
                    Value = box this.ErrorTime
                    ProviderDbType = None }
                  { WriteColumn.Name = "UserName"
                    Value = box this.UserName
                    ProviderDbType = None }
                  { WriteColumn.Name = "ErrorNumber"
                    Value = box this.ErrorNumber
                    ProviderDbType = None }
                  { WriteColumn.Name = "ErrorSeverity"
                    Value = box this.ErrorSeverity
                    ProviderDbType = None }
                  { WriteColumn.Name = "ErrorState"
                    Value = box this.ErrorState
                    ProviderDbType = None }
                  { WriteColumn.Name = "ErrorProcedure"
                    Value = box this.ErrorProcedure
                    ProviderDbType = None }
                  { WriteColumn.Name = "ErrorLine"
                    Value = box this.ErrorLine
                    ProviderDbType = None }
                  { WriteColumn.Name = "ErrorMessage"
                    Value = box this.ErrorMessage
                    ProviderDbType = None } ]

    let ErrorLog = table<ErrorLog>

    [<CLIMutable>]
    type Product =
        { ProductID: int64
          Name: Sqlite.CustomTypes.Text
          ProductNumber: Sqlite.CustomTypes.Text
          Color: Option<Sqlite.CustomTypes.Text>
          StandardCost: int64
          ListPrice: int64
          Size: Option<Sqlite.CustomTypes.Text>
          Weight: Option<int64>
          ProductCategoryID: Option<int64>
          ProductModelID: Option<int64>
          SellStartDate: System.DateTime
          SellEndDate: Option<System.DateTime>
          DiscontinuedDate: Option<System.DateTime>
          ThumbNailPhoto: Option<byte[]>
          ThumbnailPhotoFileName: Option<Sqlite.CustomTypes.Text>
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ProductID"
                    Value = box this.ProductID
                    ProviderDbType = None }
                  { WriteColumn.Name = "Name"
                    Value = box this.Name
                    ProviderDbType = None }
                  { WriteColumn.Name = "ProductNumber"
                    Value = box this.ProductNumber
                    ProviderDbType = None }
                  { WriteColumn.Name = "Color"
                    Value = box this.Color
                    ProviderDbType = None }
                  { WriteColumn.Name = "StandardCost"
                    Value = box this.StandardCost
                    ProviderDbType = None }
                  { WriteColumn.Name = "ListPrice"
                    Value = box this.ListPrice
                    ProviderDbType = None }
                  { WriteColumn.Name = "Size"
                    Value = box this.Size
                    ProviderDbType = None }
                  { WriteColumn.Name = "Weight"
                    Value = box this.Weight
                    ProviderDbType = None }
                  { WriteColumn.Name = "ProductCategoryID"
                    Value = box this.ProductCategoryID
                    ProviderDbType = None }
                  { WriteColumn.Name = "ProductModelID"
                    Value = box this.ProductModelID
                    ProviderDbType = None }
                  { WriteColumn.Name = "SellStartDate"
                    Value = box this.SellStartDate
                    ProviderDbType = None }
                  { WriteColumn.Name = "SellEndDate"
                    Value = box this.SellEndDate
                    ProviderDbType = None }
                  { WriteColumn.Name = "DiscontinuedDate"
                    Value = box this.DiscontinuedDate
                    ProviderDbType = None }
                  { WriteColumn.Name = "ThumbNailPhoto"
                    Value = box this.ThumbNailPhoto
                    ProviderDbType = None }
                  { WriteColumn.Name = "ThumbnailPhotoFileName"
                    Value = box this.ThumbnailPhotoFileName
                    ProviderDbType = None }
                  { WriteColumn.Name = "rowguid"
                    Value = box this.rowguid
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let Product = table<Product>

    [<CLIMutable>]
    type ProductCategory =
        { ProductCategoryID: int64
          ParentProductCategoryID: Option<int64>
          Name: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ProductCategoryID"
                    Value = box this.ProductCategoryID
                    ProviderDbType = None }
                  { WriteColumn.Name = "ParentProductCategoryID"
                    Value = box this.ParentProductCategoryID
                    ProviderDbType = None }
                  { WriteColumn.Name = "Name"
                    Value = box this.Name
                    ProviderDbType = None }
                  { WriteColumn.Name = "rowguid"
                    Value = box this.rowguid
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let ProductCategory = table<ProductCategory>

    [<CLIMutable>]
    type ProductDescription =
        { ProductDescriptionID: int64
          Description: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ProductDescriptionID"
                    Value = box this.ProductDescriptionID
                    ProviderDbType = None }
                  { WriteColumn.Name = "Description"
                    Value = box this.Description
                    ProviderDbType = None }
                  { WriteColumn.Name = "rowguid"
                    Value = box this.rowguid
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let ProductDescription = table<ProductDescription>

    [<CLIMutable>]
    type ProductModel =
        { ProductModelID: int64
          Name: Sqlite.CustomTypes.Text
          CatalogDescription: Option<Sqlite.CustomTypes.Text>
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ProductModelID"
                    Value = box this.ProductModelID
                    ProviderDbType = None }
                  { WriteColumn.Name = "Name"
                    Value = box this.Name
                    ProviderDbType = None }
                  { WriteColumn.Name = "CatalogDescription"
                    Value = box this.CatalogDescription
                    ProviderDbType = None }
                  { WriteColumn.Name = "rowguid"
                    Value = box this.rowguid
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let ProductModel = table<ProductModel>

    [<CLIMutable>]
    type ProductModelProductDescription =
        { ProductModelID: int64
          ProductDescriptionID: int64
          Culture: Sqlite.CustomTypes.Text
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ProductModelID"
                    Value = box this.ProductModelID
                    ProviderDbType = None }
                  { WriteColumn.Name = "ProductDescriptionID"
                    Value = box this.ProductDescriptionID
                    ProviderDbType = None }
                  { WriteColumn.Name = "Culture"
                    Value = box this.Culture
                    ProviderDbType = None }
                  { WriteColumn.Name = "rowguid"
                    Value = box this.rowguid
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let ProductModelProductDescription = table<ProductModelProductDescription>

    [<CLIMutable>]
    type SalesOrderDetail =
        { SalesOrderID: int64
          SalesOrderDetailID: int64
          OrderQty: int64
          ProductID: int64
          UnitPrice: int64
          UnitPriceDiscount: int64
          LineTotal: int64
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "SalesOrderID"
                    Value = box this.SalesOrderID
                    ProviderDbType = None }
                  { WriteColumn.Name = "SalesOrderDetailID"
                    Value = box this.SalesOrderDetailID
                    ProviderDbType = None }
                  { WriteColumn.Name = "OrderQty"
                    Value = box this.OrderQty
                    ProviderDbType = None }
                  { WriteColumn.Name = "ProductID"
                    Value = box this.ProductID
                    ProviderDbType = None }
                  { WriteColumn.Name = "UnitPrice"
                    Value = box this.UnitPrice
                    ProviderDbType = None }
                  { WriteColumn.Name = "UnitPriceDiscount"
                    Value = box this.UnitPriceDiscount
                    ProviderDbType = None }
                  { WriteColumn.Name = "LineTotal"
                    Value = box this.LineTotal
                    ProviderDbType = None }
                  { WriteColumn.Name = "rowguid"
                    Value = box this.rowguid
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let SalesOrderDetail = table<SalesOrderDetail>

    [<CLIMutable>]
    type SalesOrderHeader =
        { SalesOrderID: int64
          RevisionNumber: int64
          OrderDate: System.DateTime
          DueDate: System.DateTime
          ShipDate: Option<System.DateTime>
          Status: int64
          OnlineOrderFlag: int64
          SalesOrderNumber: string
          PurchaseOrderNumber: Option<int64>
          AccountNumber: Option<Sqlite.CustomTypes.Text>
          CustomerID: int64
          ShipToAddressID: Option<int>
          BillToAddressID: Option<int>
          ShipMethod: Sqlite.CustomTypes.Text
          CreditCardApprovalCode: Option<Sqlite.CustomTypes.Text>
          SubTotal: int64
          TaxAmt: int64
          Freight: int64
          TotalDue: int64
          Comment: Option<Sqlite.CustomTypes.Text>
          rowguid: Sqlite.CustomTypes.Text
          ModifiedDate: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "SalesOrderID"
                    Value = box this.SalesOrderID
                    ProviderDbType = None }
                  { WriteColumn.Name = "RevisionNumber"
                    Value = box this.RevisionNumber
                    ProviderDbType = None }
                  { WriteColumn.Name = "OrderDate"
                    Value = box this.OrderDate
                    ProviderDbType = None }
                  { WriteColumn.Name = "DueDate"
                    Value = box this.DueDate
                    ProviderDbType = None }
                  { WriteColumn.Name = "ShipDate"
                    Value = box this.ShipDate
                    ProviderDbType = None }
                  { WriteColumn.Name = "Status"
                    Value = box this.Status
                    ProviderDbType = None }
                  { WriteColumn.Name = "OnlineOrderFlag"
                    Value = box this.OnlineOrderFlag
                    ProviderDbType = None }
                  { WriteColumn.Name = "SalesOrderNumber"
                    Value = box this.SalesOrderNumber
                    ProviderDbType = None }
                  { WriteColumn.Name = "PurchaseOrderNumber"
                    Value = box this.PurchaseOrderNumber
                    ProviderDbType = None }
                  { WriteColumn.Name = "AccountNumber"
                    Value = box this.AccountNumber
                    ProviderDbType = None }
                  { WriteColumn.Name = "CustomerID"
                    Value = box this.CustomerID
                    ProviderDbType = None }
                  { WriteColumn.Name = "ShipToAddressID"
                    Value = box this.ShipToAddressID
                    ProviderDbType = None }
                  { WriteColumn.Name = "BillToAddressID"
                    Value = box this.BillToAddressID
                    ProviderDbType = None }
                  { WriteColumn.Name = "ShipMethod"
                    Value = box this.ShipMethod
                    ProviderDbType = None }
                  { WriteColumn.Name = "CreditCardApprovalCode"
                    Value = box this.CreditCardApprovalCode
                    ProviderDbType = None }
                  { WriteColumn.Name = "SubTotal"
                    Value = box this.SubTotal
                    ProviderDbType = None }
                  { WriteColumn.Name = "TaxAmt"
                    Value = box this.TaxAmt
                    ProviderDbType = None }
                  { WriteColumn.Name = "Freight"
                    Value = box this.Freight
                    ProviderDbType = None }
                  { WriteColumn.Name = "TotalDue"
                    Value = box this.TotalDue
                    ProviderDbType = None }
                  { WriteColumn.Name = "Comment"
                    Value = box this.Comment
                    ProviderDbType = None }
                  { WriteColumn.Name = "rowguid"
                    Value = box this.rowguid
                    ProviderDbType = None }
                  { WriteColumn.Name = "ModifiedDate"
                    Value = box this.ModifiedDate
                    ProviderDbType = None } ]

    let SalesOrderHeader = table<SalesOrderHeader>



type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqliteEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
