// This code was generated by `SqlHydra.Oracle` -- v4.1.0.
namespace Oracle.AdventureWorksNet8

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 1, 0)
    let ns = "Oracle.AdventureWorksNet8"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module OT =

    [<CLIMutable>]
    type CONTACTS =
        { CONTACT_ID: int64
          CUSTOMER_ID: Option<int64>
          EMAIL: string
          FIRST_NAME: string
          LAST_NAME: string
          PHONE: Option<string> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "CONTACT_ID"; Value = box this.CONTACT_ID; ProviderDbType = None }
                  { WriteColumn.Name = "CUSTOMER_ID"; Value = box this.CUSTOMER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "EMAIL"; Value = box this.EMAIL; ProviderDbType = None }
                  { WriteColumn.Name = "FIRST_NAME"; Value = box this.FIRST_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "LAST_NAME"; Value = box this.LAST_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "PHONE"; Value = box this.PHONE; ProviderDbType = None } ]

    let CONTACTS = table<CONTACTS>

    [<CLIMutable>]
    type COUNTRIES =
        { COUNTRY_ID: string
          COUNTRY_NAME: string
          REGION_ID: Option<int64> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "COUNTRY_ID"; Value = box this.COUNTRY_ID; ProviderDbType = None }
                  { WriteColumn.Name = "COUNTRY_NAME"; Value = box this.COUNTRY_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "REGION_ID"; Value = box this.REGION_ID; ProviderDbType = None } ]

    let COUNTRIES = table<COUNTRIES>

    [<CLIMutable>]
    type CUSTOMERS =
        { ADDRESS: Option<string>
          CREDIT_LIMIT: Option<decimal>
          CUSTOMER_ID: int64
          NAME: string
          WEBSITE: Option<string> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ADDRESS"; Value = box this.ADDRESS; ProviderDbType = None }
                  { WriteColumn.Name = "CREDIT_LIMIT"; Value = box this.CREDIT_LIMIT; ProviderDbType = None }
                  { WriteColumn.Name = "CUSTOMER_ID"; Value = box this.CUSTOMER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "NAME"; Value = box this.NAME; ProviderDbType = None }
                  { WriteColumn.Name = "WEBSITE"; Value = box this.WEBSITE; ProviderDbType = None } ]

    let CUSTOMERS = table<CUSTOMERS>

    [<CLIMutable>]
    type EMPLOYEES =
        { EMAIL: string
          EMPLOYEE_ID: int64
          FIRST_NAME: string
          HIRE_DATE: System.DateTime
          JOB_TITLE: string
          LAST_NAME: string
          MANAGER_ID: Option<int64>
          PHONE: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "EMAIL"; Value = box this.EMAIL; ProviderDbType = None }
                  { WriteColumn.Name = "EMPLOYEE_ID"; Value = box this.EMPLOYEE_ID; ProviderDbType = None }
                  { WriteColumn.Name = "FIRST_NAME"; Value = box this.FIRST_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "HIRE_DATE"; Value = box this.HIRE_DATE; ProviderDbType = None }
                  { WriteColumn.Name = "JOB_TITLE"; Value = box this.JOB_TITLE; ProviderDbType = None }
                  { WriteColumn.Name = "LAST_NAME"; Value = box this.LAST_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "MANAGER_ID"; Value = box this.MANAGER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "PHONE"; Value = box this.PHONE; ProviderDbType = None } ]

    let EMPLOYEES = table<EMPLOYEES>

    [<CLIMutable>]
    type INVENTORIES =
        { PRODUCT_ID: int64
          QUANTITY: int64
          WAREHOUSE_ID: int64 }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "PRODUCT_ID"; Value = box this.PRODUCT_ID; ProviderDbType = None }
                  { WriteColumn.Name = "QUANTITY"; Value = box this.QUANTITY; ProviderDbType = None }
                  { WriteColumn.Name = "WAREHOUSE_ID"; Value = box this.WAREHOUSE_ID; ProviderDbType = None } ]

    let INVENTORIES = table<INVENTORIES>

    [<CLIMutable>]
    type LOCATIONS =
        { ADDRESS: string
          CITY: Option<string>
          COUNTRY_ID: Option<string>
          LOCATION_ID: int64
          POSTAL_CODE: Option<string>
          STATE: Option<string> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ADDRESS"; Value = box this.ADDRESS; ProviderDbType = None }
                  { WriteColumn.Name = "CITY"; Value = box this.CITY; ProviderDbType = None }
                  { WriteColumn.Name = "COUNTRY_ID"; Value = box this.COUNTRY_ID; ProviderDbType = None }
                  { WriteColumn.Name = "LOCATION_ID"; Value = box this.LOCATION_ID; ProviderDbType = None }
                  { WriteColumn.Name = "POSTAL_CODE"; Value = box this.POSTAL_CODE; ProviderDbType = None }
                  { WriteColumn.Name = "STATE"; Value = box this.STATE; ProviderDbType = None } ]

    let LOCATIONS = table<LOCATIONS>

    [<CLIMutable>]
    type ORDERS =
        { CUSTOMER_ID: int64
          ORDER_DATE: System.DateTime
          ORDER_ID: int64
          SALESMAN_ID: Option<int64>
          STATUS: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "CUSTOMER_ID"; Value = box this.CUSTOMER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "ORDER_DATE"; Value = box this.ORDER_DATE; ProviderDbType = None }
                  { WriteColumn.Name = "ORDER_ID"; Value = box this.ORDER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "SALESMAN_ID"; Value = box this.SALESMAN_ID; ProviderDbType = None }
                  { WriteColumn.Name = "STATUS"; Value = box this.STATUS; ProviderDbType = None } ]

    let ORDERS = table<ORDERS>

    [<CLIMutable>]
    type ORDER_ITEMS =
        { ITEM_ID: int64
          ORDER_ID: int64
          PRODUCT_ID: int64
          QUANTITY: int64
          UNIT_PRICE: decimal }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ITEM_ID"; Value = box this.ITEM_ID; ProviderDbType = None }
                  { WriteColumn.Name = "ORDER_ID"; Value = box this.ORDER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "PRODUCT_ID"; Value = box this.PRODUCT_ID; ProviderDbType = None }
                  { WriteColumn.Name = "QUANTITY"; Value = box this.QUANTITY; ProviderDbType = None }
                  { WriteColumn.Name = "UNIT_PRICE"; Value = box this.UNIT_PRICE; ProviderDbType = None } ]

    let ORDER_ITEMS = table<ORDER_ITEMS>

    [<CLIMutable>]
    type PRODUCTS =
        { CATEGORY_ID: int64
          DESCRIPTION: Option<string>
          LIST_PRICE: Option<decimal>
          PRODUCT_ID: int64
          PRODUCT_NAME: string
          STANDARD_COST: Option<decimal> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "CATEGORY_ID"; Value = box this.CATEGORY_ID; ProviderDbType = None }
                  { WriteColumn.Name = "DESCRIPTION"; Value = box this.DESCRIPTION; ProviderDbType = None }
                  { WriteColumn.Name = "LIST_PRICE"; Value = box this.LIST_PRICE; ProviderDbType = None }
                  { WriteColumn.Name = "PRODUCT_ID"; Value = box this.PRODUCT_ID; ProviderDbType = None }
                  { WriteColumn.Name = "PRODUCT_NAME"; Value = box this.PRODUCT_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "STANDARD_COST"; Value = box this.STANDARD_COST; ProviderDbType = None } ]

    let PRODUCTS = table<PRODUCTS>

    [<CLIMutable>]
    type PRODUCT_CATEGORIES =
        { CATEGORY_ID: int64
          CATEGORY_NAME: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "CATEGORY_ID"; Value = box this.CATEGORY_ID; ProviderDbType = None }
                  { WriteColumn.Name = "CATEGORY_NAME"; Value = box this.CATEGORY_NAME; ProviderDbType = None } ]

    let PRODUCT_CATEGORIES = table<PRODUCT_CATEGORIES>

    [<CLIMutable>]
    type REGIONS =
        { REGION_ID: int64
          REGION_NAME: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "REGION_ID"; Value = box this.REGION_ID; ProviderDbType = None }
                  { WriteColumn.Name = "REGION_NAME"; Value = box this.REGION_NAME; ProviderDbType = None } ]

    let REGIONS = table<REGIONS>

    [<CLIMutable>]
    type WAREHOUSES =
        { LOCATION_ID: Option<int64>
          WAREHOUSE_ID: int64
          WAREHOUSE_NAME: Option<string> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "LOCATION_ID"; Value = box this.LOCATION_ID; ProviderDbType = None }
                  { WriteColumn.Name = "WAREHOUSE_ID"; Value = box this.WAREHOUSE_ID; ProviderDbType = None }
                  { WriteColumn.Name = "WAREHOUSE_NAME"; Value = box this.WAREHOUSE_NAME; ProviderDbType = None } ]

    let WAREHOUSES = table<WAREHOUSES>



type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.OracleEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Oracle.ManagedDataAccess.Client.OracleConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext; OpenContextAsync = openContextAsync }
