// This code was generated by `SqlHydra.Oracle` -- v4.1.0.
namespace Oracle.AdventureWorksNet9

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 1, 0)
    let ns = "Oracle.AdventureWorksNet9"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module OT =

    [<CLIMutable>]
    type CONTACTS =
        { CONTACT_ID: int64
          CUSTOMER_ID: Option<int64>
          EMAIL: string
          FIRST_NAME: string
          LAST_NAME: string
          PHONE: Option<string> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "CONTACT_ID"; Value = box this.CONTACT_ID; ProviderDbType = None }
                  { WriteColumn.Name = "CUSTOMER_ID"; Value = box this.CUSTOMER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "EMAIL"; Value = box this.EMAIL; ProviderDbType = None }
                  { WriteColumn.Name = "FIRST_NAME"; Value = box this.FIRST_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "LAST_NAME"; Value = box this.LAST_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "PHONE"; Value = box this.PHONE; ProviderDbType = None } ]

    let CONTACTS = table<CONTACTS>

    [<CLIMutable>]
    type COUNTRIES =
        { COUNTRY_ID: string
          COUNTRY_NAME: string
          REGION_ID: Option<int64> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "COUNTRY_ID"; Value = box this.COUNTRY_ID; ProviderDbType = None }
                  { WriteColumn.Name = "COUNTRY_NAME"; Value = box this.COUNTRY_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "REGION_ID"; Value = box this.REGION_ID; ProviderDbType = None } ]

    let COUNTRIES = table<COUNTRIES>

    [<CLIMutable>]
    type CUSTOMERS =
        { ADDRESS: Option<string>
          CREDIT_LIMIT: Option<decimal>
          CUSTOMER_ID: int64
          NAME: string
          WEBSITE: Option<string> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ADDRESS"; Value = box this.ADDRESS; ProviderDbType = None }
                  { WriteColumn.Name = "CREDIT_LIMIT"; Value = box this.CREDIT_LIMIT; ProviderDbType = None }
                  { WriteColumn.Name = "CUSTOMER_ID"; Value = box this.CUSTOMER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "NAME"; Value = box this.NAME; ProviderDbType = None }
                  { WriteColumn.Name = "WEBSITE"; Value = box this.WEBSITE; ProviderDbType = None } ]

    let CUSTOMERS = table<CUSTOMERS>

    [<CLIMutable>]
    type EMPLOYEES =
        { EMAIL: string
          EMPLOYEE_ID: int64
          FIRST_NAME: string
          HIRE_DATE: System.DateTime
          JOB_TITLE: string
          LAST_NAME: string
          MANAGER_ID: Option<int64>
          PHONE: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "EMAIL"; Value = box this.EMAIL; ProviderDbType = None }
                  { WriteColumn.Name = "EMPLOYEE_ID"; Value = box this.EMPLOYEE_ID; ProviderDbType = None }
                  { WriteColumn.Name = "FIRST_NAME"; Value = box this.FIRST_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "HIRE_DATE"; Value = box this.HIRE_DATE; ProviderDbType = None }
                  { WriteColumn.Name = "JOB_TITLE"; Value = box this.JOB_TITLE; ProviderDbType = None }
                  { WriteColumn.Name = "LAST_NAME"; Value = box this.LAST_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "MANAGER_ID"; Value = box this.MANAGER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "PHONE"; Value = box this.PHONE; ProviderDbType = None } ]

    let EMPLOYEES = table<EMPLOYEES>

    [<CLIMutable>]
    type INVENTORIES =
        { PRODUCT_ID: int64
          QUANTITY: int64
          WAREHOUSE_ID: int64 }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "PRODUCT_ID"; Value = box this.PRODUCT_ID; ProviderDbType = None }
                  { WriteColumn.Name = "QUANTITY"; Value = box this.QUANTITY; ProviderDbType = None }
                  { WriteColumn.Name = "WAREHOUSE_ID"; Value = box this.WAREHOUSE_ID; ProviderDbType = None } ]

    let INVENTORIES = table<INVENTORIES>

    [<CLIMutable>]
    type LOCATIONS =
        { ADDRESS: string
          CITY: Option<string>
          COUNTRY_ID: Option<string>
          LOCATION_ID: int64
          POSTAL_CODE: Option<string>
          STATE: Option<string> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ADDRESS"; Value = box this.ADDRESS; ProviderDbType = None }
                  { WriteColumn.Name = "CITY"; Value = box this.CITY; ProviderDbType = None }
                  { WriteColumn.Name = "COUNTRY_ID"; Value = box this.COUNTRY_ID; ProviderDbType = None }
                  { WriteColumn.Name = "LOCATION_ID"; Value = box this.LOCATION_ID; ProviderDbType = None }
                  { WriteColumn.Name = "POSTAL_CODE"; Value = box this.POSTAL_CODE; ProviderDbType = None }
                  { WriteColumn.Name = "STATE"; Value = box this.STATE; ProviderDbType = None } ]

    let LOCATIONS = table<LOCATIONS>

    [<CLIMutable>]
    type ORDERS =
        { CUSTOMER_ID: int64
          ORDER_DATE: System.DateTime
          ORDER_ID: int64
          SALESMAN_ID: Option<int64>
          STATUS: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "CUSTOMER_ID"; Value = box this.CUSTOMER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "ORDER_DATE"; Value = box this.ORDER_DATE; ProviderDbType = None }
                  { WriteColumn.Name = "ORDER_ID"; Value = box this.ORDER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "SALESMAN_ID"; Value = box this.SALESMAN_ID; ProviderDbType = None }
                  { WriteColumn.Name = "STATUS"; Value = box this.STATUS; ProviderDbType = None } ]

    let ORDERS = table<ORDERS>

    [<CLIMutable>]
    type ORDER_ITEMS =
        { ITEM_ID: int64
          ORDER_ID: int64
          PRODUCT_ID: int64
          QUANTITY: int64
          UNIT_PRICE: decimal }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "ITEM_ID"; Value = box this.ITEM_ID; ProviderDbType = None }
                  { WriteColumn.Name = "ORDER_ID"; Value = box this.ORDER_ID; ProviderDbType = None }
                  { WriteColumn.Name = "PRODUCT_ID"; Value = box this.PRODUCT_ID; ProviderDbType = None }
                  { WriteColumn.Name = "QUANTITY"; Value = box this.QUANTITY; ProviderDbType = None }
                  { WriteColumn.Name = "UNIT_PRICE"; Value = box this.UNIT_PRICE; ProviderDbType = None } ]

    let ORDER_ITEMS = table<ORDER_ITEMS>

    [<CLIMutable>]
    type PRODUCTS =
        { CATEGORY_ID: int64
          DESCRIPTION: Option<string>
          LIST_PRICE: Option<decimal>
          PRODUCT_ID: int64
          PRODUCT_NAME: string
          STANDARD_COST: Option<decimal> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "CATEGORY_ID"; Value = box this.CATEGORY_ID; ProviderDbType = None }
                  { WriteColumn.Name = "DESCRIPTION"; Value = box this.DESCRIPTION; ProviderDbType = None }
                  { WriteColumn.Name = "LIST_PRICE"; Value = box this.LIST_PRICE; ProviderDbType = None }
                  { WriteColumn.Name = "PRODUCT_ID"; Value = box this.PRODUCT_ID; ProviderDbType = None }
                  { WriteColumn.Name = "PRODUCT_NAME"; Value = box this.PRODUCT_NAME; ProviderDbType = None }
                  { WriteColumn.Name = "STANDARD_COST"; Value = box this.STANDARD_COST; ProviderDbType = None } ]

    let PRODUCTS = table<PRODUCTS>

    [<CLIMutable>]
    type PRODUCT_CATEGORIES =
        { CATEGORY_ID: int64
          CATEGORY_NAME: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "CATEGORY_ID"; Value = box this.CATEGORY_ID; ProviderDbType = None }
                  { WriteColumn.Name = "CATEGORY_NAME"; Value = box this.CATEGORY_NAME; ProviderDbType = None } ]

    let PRODUCT_CATEGORIES = table<PRODUCT_CATEGORIES>

    [<CLIMutable>]
    type REGIONS =
        { REGION_ID: int64
          REGION_NAME: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "REGION_ID"; Value = box this.REGION_ID; ProviderDbType = None }
                  { WriteColumn.Name = "REGION_NAME"; Value = box this.REGION_NAME; ProviderDbType = None } ]

    let REGIONS = table<REGIONS>

    [<CLIMutable>]
    type WAREHOUSES =
        { LOCATION_ID: Option<int64>
          WAREHOUSE_ID: int64
          WAREHOUSE_NAME: Option<string> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "LOCATION_ID"; Value = box this.LOCATION_ID; ProviderDbType = None }
                  { WriteColumn.Name = "WAREHOUSE_ID"; Value = box this.WAREHOUSE_ID; ProviderDbType = None }
                  { WriteColumn.Name = "WAREHOUSE_NAME"; Value = box this.WAREHOUSE_NAME; ProviderDbType = None } ]

    let WAREHOUSES = table<WAREHOUSES>

    /// Left-views for `leftJoin`: each table record with every column in its nullable form,
    /// so an unmatched row reads as None per column instead of one Option around the record.
    module LeftJoined =
        type private ``CONTACTS (base)`` = CONTACTS

        [<CLIMutable; NoEquality; NoComparison>]
        type CONTACTS =
            { CONTACT_ID: Option<int64>
              CUSTOMER_ID: Option<int64>
              EMAIL: Option<string>
              FIRST_NAME: Option<string>
              LAST_NAME: Option<string>
              PHONE: Option<string> }

            interface ILeftViewOf<``CONTACTS (base)``>

        let CONTACTS = leftTable<``CONTACTS (base)``, CONTACTS>

        type private ``COUNTRIES (base)`` = COUNTRIES

        [<CLIMutable; NoEquality; NoComparison>]
        type COUNTRIES =
            { COUNTRY_ID: Option<string>
              COUNTRY_NAME: Option<string>
              REGION_ID: Option<int64> }

            interface ILeftViewOf<``COUNTRIES (base)``>

        let COUNTRIES = leftTable<``COUNTRIES (base)``, COUNTRIES>

        type private ``CUSTOMERS (base)`` = CUSTOMERS

        [<CLIMutable; NoEquality; NoComparison>]
        type CUSTOMERS =
            { ADDRESS: Option<string>
              CREDIT_LIMIT: Option<decimal>
              CUSTOMER_ID: Option<int64>
              NAME: Option<string>
              WEBSITE: Option<string> }

            interface ILeftViewOf<``CUSTOMERS (base)``>

        let CUSTOMERS = leftTable<``CUSTOMERS (base)``, CUSTOMERS>

        type private ``EMPLOYEES (base)`` = EMPLOYEES

        [<CLIMutable; NoEquality; NoComparison>]
        type EMPLOYEES =
            { EMAIL: Option<string>
              EMPLOYEE_ID: Option<int64>
              FIRST_NAME: Option<string>
              HIRE_DATE: Option<System.DateTime>
              JOB_TITLE: Option<string>
              LAST_NAME: Option<string>
              MANAGER_ID: Option<int64>
              PHONE: Option<string> }

            interface ILeftViewOf<``EMPLOYEES (base)``>

        let EMPLOYEES = leftTable<``EMPLOYEES (base)``, EMPLOYEES>

        type private ``INVENTORIES (base)`` = INVENTORIES

        [<CLIMutable; NoEquality; NoComparison>]
        type INVENTORIES =
            { PRODUCT_ID: Option<int64>
              QUANTITY: Option<int64>
              WAREHOUSE_ID: Option<int64> }

            interface ILeftViewOf<``INVENTORIES (base)``>

        let INVENTORIES = leftTable<``INVENTORIES (base)``, INVENTORIES>

        type private ``LOCATIONS (base)`` = LOCATIONS

        [<CLIMutable; NoEquality; NoComparison>]
        type LOCATIONS =
            { ADDRESS: Option<string>
              CITY: Option<string>
              COUNTRY_ID: Option<string>
              LOCATION_ID: Option<int64>
              POSTAL_CODE: Option<string>
              STATE: Option<string> }

            interface ILeftViewOf<``LOCATIONS (base)``>

        let LOCATIONS = leftTable<``LOCATIONS (base)``, LOCATIONS>

        type private ``ORDERS (base)`` = ORDERS

        [<CLIMutable; NoEquality; NoComparison>]
        type ORDERS =
            { CUSTOMER_ID: Option<int64>
              ORDER_DATE: Option<System.DateTime>
              ORDER_ID: Option<int64>
              SALESMAN_ID: Option<int64>
              STATUS: Option<string> }

            interface ILeftViewOf<``ORDERS (base)``>

        let ORDERS = leftTable<``ORDERS (base)``, ORDERS>

        type private ``ORDER_ITEMS (base)`` = ORDER_ITEMS

        [<CLIMutable; NoEquality; NoComparison>]
        type ORDER_ITEMS =
            { ITEM_ID: Option<int64>
              ORDER_ID: Option<int64>
              PRODUCT_ID: Option<int64>
              QUANTITY: Option<int64>
              UNIT_PRICE: Option<decimal> }

            interface ILeftViewOf<``ORDER_ITEMS (base)``>

        let ORDER_ITEMS = leftTable<``ORDER_ITEMS (base)``, ORDER_ITEMS>

        type private ``PRODUCTS (base)`` = PRODUCTS

        [<CLIMutable; NoEquality; NoComparison>]
        type PRODUCTS =
            { CATEGORY_ID: Option<int64>
              DESCRIPTION: Option<string>
              LIST_PRICE: Option<decimal>
              PRODUCT_ID: Option<int64>
              PRODUCT_NAME: Option<string>
              STANDARD_COST: Option<decimal> }

            interface ILeftViewOf<``PRODUCTS (base)``>

        let PRODUCTS = leftTable<``PRODUCTS (base)``, PRODUCTS>

        type private ``PRODUCT_CATEGORIES (base)`` = PRODUCT_CATEGORIES

        [<CLIMutable; NoEquality; NoComparison>]
        type PRODUCT_CATEGORIES =
            { CATEGORY_ID: Option<int64>
              CATEGORY_NAME: Option<string> }

            interface ILeftViewOf<``PRODUCT_CATEGORIES (base)``>

        let PRODUCT_CATEGORIES =
            leftTable<``PRODUCT_CATEGORIES (base)``, PRODUCT_CATEGORIES>

        type private ``REGIONS (base)`` = REGIONS

        [<CLIMutable; NoEquality; NoComparison>]
        type REGIONS =
            { REGION_ID: Option<int64>
              REGION_NAME: Option<string> }

            interface ILeftViewOf<``REGIONS (base)``>

        let REGIONS = leftTable<``REGIONS (base)``, REGIONS>

        type private ``WAREHOUSES (base)`` = WAREHOUSES

        [<CLIMutable; NoEquality; NoComparison>]
        type WAREHOUSES =
            { LOCATION_ID: Option<int64>
              WAREHOUSE_ID: Option<int64>
              WAREHOUSE_NAME: Option<string> }

            interface ILeftViewOf<``WAREHOUSES (base)``>

        let WAREHOUSES = leftTable<``WAREHOUSES (base)``, WAREHOUSES>


[<AutoOpen>]
module LeftViewExtensions =
    type OT.LeftJoined.CONTACTS with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.CONTACTS option =
            match this.CONTACT_ID with
            | Some value ->
                let record: OT.CONTACTS =
                    { CONTACT_ID = value; CUSTOMER_ID = this.CUSTOMER_ID; EMAIL = this.EMAIL.Value; FIRST_NAME = this.FIRST_NAME.Value; LAST_NAME = this.LAST_NAME.Value; PHONE = this.PHONE }

                Some record
            | None -> None

    type OT.LeftJoined.COUNTRIES with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.COUNTRIES option =
            match this.COUNTRY_ID with
            | Some value ->
                let record: OT.COUNTRIES =
                    { COUNTRY_ID = value; COUNTRY_NAME = this.COUNTRY_NAME.Value; REGION_ID = this.REGION_ID }

                Some record
            | None -> None

    type OT.LeftJoined.CUSTOMERS with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.CUSTOMERS option =
            match this.CUSTOMER_ID with
            | Some value ->
                let record: OT.CUSTOMERS =
                    { ADDRESS = this.ADDRESS; CREDIT_LIMIT = this.CREDIT_LIMIT; CUSTOMER_ID = value; NAME = this.NAME.Value; WEBSITE = this.WEBSITE }

                Some record
            | None -> None

    type OT.LeftJoined.EMPLOYEES with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.EMPLOYEES option =
            match this.EMPLOYEE_ID with
            | Some value ->
                let record: OT.EMPLOYEES =
                    { EMAIL = this.EMAIL.Value
                      EMPLOYEE_ID = value
                      FIRST_NAME = this.FIRST_NAME.Value
                      HIRE_DATE = this.HIRE_DATE.Value
                      JOB_TITLE = this.JOB_TITLE.Value
                      LAST_NAME = this.LAST_NAME.Value
                      MANAGER_ID = this.MANAGER_ID
                      PHONE = this.PHONE.Value }

                Some record
            | None -> None

    type OT.LeftJoined.INVENTORIES with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.INVENTORIES option =
            match this.PRODUCT_ID with
            | Some value ->
                let record: OT.INVENTORIES =
                    { PRODUCT_ID = value; QUANTITY = this.QUANTITY.Value; WAREHOUSE_ID = this.WAREHOUSE_ID.Value }

                Some record
            | None -> None

    type OT.LeftJoined.LOCATIONS with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.LOCATIONS option =
            match this.LOCATION_ID with
            | Some value ->
                let record: OT.LOCATIONS =
                    { ADDRESS = this.ADDRESS.Value; CITY = this.CITY; COUNTRY_ID = this.COUNTRY_ID; LOCATION_ID = value; POSTAL_CODE = this.POSTAL_CODE; STATE = this.STATE }

                Some record
            | None -> None

    type OT.LeftJoined.ORDERS with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.ORDERS option =
            match this.ORDER_ID with
            | Some value ->
                let record: OT.ORDERS =
                    { CUSTOMER_ID = this.CUSTOMER_ID.Value; ORDER_DATE = this.ORDER_DATE.Value; ORDER_ID = value; SALESMAN_ID = this.SALESMAN_ID; STATUS = this.STATUS.Value }

                Some record
            | None -> None

    type OT.LeftJoined.ORDER_ITEMS with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.ORDER_ITEMS option =
            match this.ITEM_ID with
            | Some value ->
                let record: OT.ORDER_ITEMS =
                    { ITEM_ID = value; ORDER_ID = this.ORDER_ID.Value; PRODUCT_ID = this.PRODUCT_ID.Value; QUANTITY = this.QUANTITY.Value; UNIT_PRICE = this.UNIT_PRICE.Value }

                Some record
            | None -> None

    type OT.LeftJoined.PRODUCTS with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.PRODUCTS option =
            match this.PRODUCT_ID with
            | Some value ->
                let record: OT.PRODUCTS =
                    { CATEGORY_ID = this.CATEGORY_ID.Value
                      DESCRIPTION = this.DESCRIPTION
                      LIST_PRICE = this.LIST_PRICE
                      PRODUCT_ID = value
                      PRODUCT_NAME = this.PRODUCT_NAME.Value
                      STANDARD_COST = this.STANDARD_COST }

                Some record
            | None -> None

    type OT.LeftJoined.PRODUCT_CATEGORIES with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.PRODUCT_CATEGORIES option =
            match this.CATEGORY_ID with
            | Some value ->
                let record: OT.PRODUCT_CATEGORIES =
                    { CATEGORY_ID = value; CATEGORY_NAME = this.CATEGORY_NAME.Value }

                Some record
            | None -> None

    type OT.LeftJoined.REGIONS with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.REGIONS option =
            match this.REGION_ID with
            | Some value ->
                let record: OT.REGIONS = { REGION_ID = value; REGION_NAME = this.REGION_NAME.Value }
                Some record
            | None -> None

    type OT.LeftJoined.WAREHOUSES with
        /// Recovers the whole-record option after materialization (pure .NET, not SQL):
        /// Some when the left join matched, None when it did not.
        member this.ToOption() : OT.WAREHOUSES option =
            match this.WAREHOUSE_ID with
            | Some value ->
                let record: OT.WAREHOUSES =
                    { LOCATION_ID = this.LOCATION_ID; WAREHOUSE_ID = value; WAREHOUSE_NAME = this.WAREHOUSE_NAME }

                Some record
            | None -> None




type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.OracleEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Oracle.ManagedDataAccess.Client.OracleConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext; OpenContextAsync = openContextAsync }
