-- Connect as SYSTEM and create tables in OT schema
-- This script will be run by the container as SYSTEM user

-- First, ensure we're in the right PDB (for Oracle 21c XE it's XEPDB1)
ALTER SESSION SET CONTAINER = XEPDB1;

-- Grant necessary privileges to OT user if not already granted
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, UNLIMITED TABLESPACE TO OT;

-- Now create all tables with OT. prefix to ensure they're created in OT schema
-- regions
CREATE TABLE OT.regions
  (
    region_id NUMBER(12,0) GENERATED BY DEFAULT AS IDENTITY
    START WITH 5 PRIMARY KEY,
    region_name VARCHAR2( 50 ) NOT NULL
  );

-- countries table
CREATE TABLE OT.countries
  (
    country_id   CHAR( 2 ) PRIMARY KEY  ,
    country_name VARCHAR2( 40 ) NOT NULL,
    region_id    NUMBER(12,0)                 , -- fk
    CONSTRAINT fk_countries_regions FOREIGN KEY( region_id )
      REFERENCES OT.regions( region_id ) 
      ON DELETE CASCADE
  );

-- location
CREATE TABLE OT.locations
  (
    location_id NUMBER(12,0) GENERATED BY DEFAULT AS IDENTITY START WITH 24 
                PRIMARY KEY       ,
    address     VARCHAR2( 255 ) NOT NULL,
    postal_code VARCHAR2( 20 )          ,
    city        VARCHAR2( 50 )          ,
    state       VARCHAR2( 50 )          ,
    country_id  CHAR( 2 )               , -- fk
    CONSTRAINT fk_locations_countries 
      FOREIGN KEY( country_id )
      REFERENCES OT.countries( country_id ) 
      ON DELETE CASCADE
  );

-- warehouses
CREATE TABLE OT.warehouses
  (
    warehouse_id NUMBER(12,0) 
                 GENERATED BY DEFAULT AS IDENTITY START WITH 10 
                 PRIMARY KEY,
    warehouse_name VARCHAR( 255 ) ,
    location_id    NUMBER(12, 0), -- fk
    CONSTRAINT fk_warehouses_locations 
      FOREIGN KEY( location_id )
      REFERENCES OT.locations( location_id ) 
      ON DELETE CASCADE
  );

-- employees
CREATE TABLE OT.employees
  (
    employee_id NUMBER(12,0) 
                GENERATED BY DEFAULT AS IDENTITY START WITH 108 
                PRIMARY KEY,
    first_name VARCHAR( 255 ) NOT NULL,
    last_name  VARCHAR( 255 ) NOT NULL,
    email      VARCHAR( 255 ) NOT NULL,
    phone      VARCHAR( 50 ) NOT NULL ,
    hire_date  DATE NOT NULL          ,
    manager_id NUMBER( 12, 0 )        , -- fk
    job_title  VARCHAR( 255 ) NOT NULL,
    CONSTRAINT fk_employees_manager 
        FOREIGN KEY( manager_id )
        REFERENCES OT.employees( employee_id )
        ON DELETE CASCADE
  );

-- product category
CREATE TABLE OT.product_categories
  (
    category_id NUMBER(12,0) 
                GENERATED BY DEFAULT AS IDENTITY START WITH 6 
                PRIMARY KEY,
    category_name VARCHAR2( 255 ) NOT NULL
  );

-- products table
CREATE TABLE OT.products
  (
    product_id NUMBER(12,0) 
               GENERATED BY DEFAULT AS IDENTITY START WITH 289 
               PRIMARY KEY,
    product_name  VARCHAR2( 255 ) NOT NULL,
    description   VARCHAR2( 2000 )        ,
    standard_cost NUMBER( 9, 4 )          ,
    list_price    NUMBER( 9, 4 )          ,
    category_id   NUMBER(12,0) NOT NULL   ,
    CONSTRAINT fk_products_categories 
      FOREIGN KEY( category_id )
      REFERENCES OT.product_categories( category_id ) 
      ON DELETE CASCADE
  );

-- customers
CREATE TABLE OT.customers
  (
    customer_id NUMBER(12,0) 
                GENERATED BY DEFAULT AS IDENTITY START WITH 320 
                PRIMARY KEY,
    name         VARCHAR2( 255 ) NOT NULL,
    address      VARCHAR2( 255 )         ,
    website      VARCHAR2( 255 )         ,
    credit_limit NUMBER( 8, 4 )
  );

-- contacts
CREATE TABLE OT.contacts
  (
    contact_id NUMBER(12,0) 
               GENERATED BY DEFAULT AS IDENTITY START WITH 320 
               PRIMARY KEY,
    first_name  VARCHAR2( 255 ) NOT NULL,
    last_name   VARCHAR2( 255 ) NOT NULL,
    email       VARCHAR2( 255 ) NOT NULL,
    phone       VARCHAR2( 20 )          ,
    customer_id NUMBER(12,0)            ,
    CONSTRAINT fk_contacts_customers 
      FOREIGN KEY( customer_id )
      REFERENCES OT.customers( customer_id ) 
      ON DELETE CASCADE
  );

-- orders table
CREATE TABLE OT.orders
  (
    order_id NUMBER(12,0) 
             GENERATED BY DEFAULT AS IDENTITY START WITH 106 
             PRIMARY KEY,
    customer_id NUMBER( 12, 0 ) NOT NULL, -- fk
    status      VARCHAR( 20 ) NOT NULL ,
    salesman_id NUMBER( 12, 0 )         , -- fk
    order_date  DATE NOT NULL          ,
    CONSTRAINT fk_orders_customers 
      FOREIGN KEY( customer_id )
      REFERENCES OT.customers( customer_id )
      ON DELETE CASCADE,
    CONSTRAINT fk_orders_employees 
      FOREIGN KEY( salesman_id )
      REFERENCES OT.employees( employee_id ) 
      ON DELETE SET NULL
  );

-- order items
CREATE TABLE OT.order_items
  (
    order_id   NUMBER( 12, 0 )                                , -- fk
    item_id    NUMBER( 12, 0 )                                ,
    product_id NUMBER( 12, 0 ) NOT NULL                       , -- fk
    quantity   NUMBER( 10, 0 ) NOT NULL                        ,
    unit_price NUMBER( 8, 4 ) NOT NULL                        ,
    CONSTRAINT pk_order_items 
      PRIMARY KEY( order_id, item_id ),
    CONSTRAINT fk_order_items_products 
      FOREIGN KEY( product_id )
      REFERENCES OT.products( product_id ) 
      ON DELETE CASCADE,
    CONSTRAINT fk_order_items_orders 
      FOREIGN KEY( order_id )
      REFERENCES OT.orders( order_id ) 
      ON DELETE CASCADE
  );

-- inventories
CREATE TABLE OT.inventories
  (
    product_id   NUMBER( 12, 0 )        , -- fk
    warehouse_id NUMBER( 12, 0 )        , -- fk
    quantity     NUMBER( 10, 0 ) NOT NULL,
    CONSTRAINT pk_inventories 
      PRIMARY KEY( product_id, warehouse_id ),
    CONSTRAINT fk_inventories_products 
      FOREIGN KEY( product_id )
      REFERENCES OT.products( product_id ) 
      ON DELETE CASCADE,
    CONSTRAINT fk_inventories_warehouses 
      FOREIGN KEY( warehouse_id )
      REFERENCES OT.warehouses( warehouse_id ) 
      ON DELETE CASCADE
  );

COMMIT;

-- Grant permissions to OT user to access their own tables
GRANT ALL PRIVILEGES ON OT.regions TO OT;
GRANT ALL PRIVILEGES ON OT.countries TO OT;
GRANT ALL PRIVILEGES ON OT.locations TO OT;
GRANT ALL PRIVILEGES ON OT.warehouses TO OT;
GRANT ALL PRIVILEGES ON OT.employees TO OT;
GRANT ALL PRIVILEGES ON OT.product_categories TO OT;
GRANT ALL PRIVILEGES ON OT.products TO OT;
GRANT ALL PRIVILEGES ON OT.customers TO OT;
GRANT ALL PRIVILEGES ON OT.contacts TO OT;
GRANT ALL PRIVILEGES ON OT.orders TO OT;
GRANT ALL PRIVILEGES ON OT.order_items TO OT;
GRANT ALL PRIVILEGES ON OT.inventories TO OT;

/