open SqlHydra
open SqlHydra.Sqlite
open Argu
open Schema

let sqlHydraId  = "SqlHydra.Sqlite"
let command     = "sqlhydra-sqlite"
let comment     = $"// This code was generated by {sqlHydraId}."

[<EntryPoint>]
let main argv =

    let cfg = 
        match argv with
        | [| connStr; nmspace; outputFile |] -> 

            { Config.ConnectionString = connStr
              Config.Namespace = nmspace
              Config.OutputFile = outputFile
              Config.IsCLIMutable = false }

        | _ ->
            let parser = ArgumentParser.Create<Schema.Arguments>(command)
            let args = parser.Parse(argv)

            { Config.ConnectionString = args.GetResult(Arguments.Connection, "required")
              Config.Namespace = args.GetResult(Arguments.Namespace, "Generated")
              Config.OutputFile = args.GetResult(Arguments.Output, "required")
              Config.IsCLIMutable = args.Contains(Arguments.CLI_Mutable) }

    let formattedCode = 
        SqliteSchemaProvider.getSchema cfg
        |> SchemaGenerator.generateModule cfg
        |> SchemaGenerator.toFormattedCode cfg comment

    System.IO.File.WriteAllText(cfg.OutputFile, formattedCode)
    0
