module SqlHydra.Sqlite.SqliteDataTypes

let typeMappingsByName =
    [ "smallint"        ,"System.Int16"
      "int"             ,"int"
      "real"            ,"double"
      "single"          ,"System.Single"
      "float"           ,"double"
      "double"          ,"double"
      "money"           ,"decimal"
      "currency"        ,"decimal"
      "decimal"         ,"decimal"
      "numeric"         ,"decimal"
      "bit"             ,"bool"
      "yesno"           ,"bool"
      "logical"         ,"bool"
      "bool"            ,"bool"
      "boolean"         ,"bool"
      "tinyint"         ,"byte"
      "integer"         ,"System.Int64"    
      "counter"         ,"System.Int64"    
      "autoincrement"   ,"System.Int64"    
      "identity"        ,"System.Int64"    
      "long"            ,"System.Int64"    
      "bigint"          ,"System.Int64"    
      "binary"          ,"byte[]"   
      "varbinary"       ,"byte[]"   
      "blob"            ,"byte[]"   
      "image"           ,"byte[]"   
      "general"         ,"byte[]"   
      "oleobject"       ,"byte[]"   
      "varchar"         ,"string"   
      "nvarchar"        ,"string"   
      "memo"            ,"string"   
      "longtext"        ,"string"   
      "note"            ,"string"   
      "text"            ,"string"   
      "ntext"           ,"string"   
      "string"          ,"string"   
      "char"            ,"string"   
      "nchar"           ,"string"   
      "datetime"        ,"System.DateTime" 
      "smalldate"       ,"System.DateTime" 
      "timestamp"       ,"System.DateTime" 
      "date"            ,"System.DateTime" 
      "time"            ,"System.DateTime" 
      "uniqueidentifier","System.Guid"     
      "guid"            ,"System.Guid" ]
    |> Map.ofList

let tryFindClrType (dataType: string) =
    typeMappingsByName.TryFind (dataType.ToLower())

