module SqlHydra.Sqlite.SqliteDataTypes

let typeMappingsByName =
    [ "smallint"        ,"System.Int16"
      "int"             ,"System.Int32"
      "real"            ,"System.Double"
      "single"          ,"System.Single"
      "float"           ,"System.Double"
      "double"          ,"System.Double"
      "money"           ,"System.Decimal"
      "currency"        ,"System.Decimal"
      "decimal"         ,"System.Decimal"
      "numeric"         ,"System.Decimal"
      "bit"             ,"System.Boolean"
      "yesno"           ,"System.Boolean"
      "logical"         ,"System.Boolean"
      "bool"            ,"System.Boolean"
      "boolean"         ,"System.Boolean"
      "tinyint"         ,"System.Byte"
      "integer"         ,"System.Int64"    
      "counter"         ,"System.Int64"    
      "autoincrement"   ,"System.Int64"    
      "identity"        ,"System.Int64"    
      "long"            ,"System.Int64"    
      "bigint"          ,"System.Int64"    
      "binary"          ,"System.Byte[]"   
      "varbinary"       ,"System.Byte[]"   
      "blob"            ,"System.Byte[]"   
      "image"           ,"System.Byte[]"   
      "general"         ,"System.Byte[]"   
      "oleobject"       ,"System.Byte[]"   
      "varchar"         ,"System.String"   
      "nvarchar"        ,"System.String"   
      "memo"            ,"System.String"   
      "longtext"        ,"System.String"   
      "note"            ,"System.String"   
      "text"            ,"System.String"   
      "ntext"           ,"System.String"   
      "string"          ,"System.String"   
      "char"            ,"System.String"   
      "nchar"           ,"System.String"   
      "datetime"        ,"System.DateTime" 
      "smalldate"       ,"System.DateTime" 
      "timestamp"       ,"System.DateTime" 
      "date"            ,"System.DateTime" 
      "time"            ,"System.DateTime" 
      "uniqueidentifier","System.Guid"     
      "guid"            ,"System.Guid" ]
    |> Map.ofList

let tryFindClrType (dataType: string) =
    typeMappingsByName.TryFind (dataType.ToLower())

