open SqlHydra
open SqlHydra.SqlServer

[<EntryPoint>]
let main argv =
    match argv with
    | [| connectionString; nmspace; outputFilePath |] -> 

        let comment = "// This code was generated by SqlHydra.SqlServer."
        let formattedCode = 
            SqlServerSchemaProvider.getSchema connectionString
            |> SchemaGenerator.generateModule nmspace
            |> SchemaGenerator.toFormattedCode nmspace comment

        System.IO.File.WriteAllText(outputFilePath, formattedCode)
        0

    | _ ->
        failwithf "SqlHydra.SqlServer expected 'connectionString' and 'outputFilePath' args"
