TRUNCATE TABLE DimCurrency;

INSERT INTO DimCurrency(CurrencyKey, CurrencyAlternateKey, CurrencyName)
SELECT 1, N'AFA', N'Afghani' FROM DUAL UNION ALL
SELECT 2, N'DZD', N'Algerian Dinar' FROM DUAL UNION ALL
SELECT 3, N'ARS', N'Argentine Peso' FROM DUAL UNION ALL
SELECT 4, N'AMD', N'Armenian Dram' FROM DUAL UNION ALL
SELECT 5, N'AWG', N'Aruban Guilder' FROM DUAL UNION ALL
SELECT 6, N'AUD', N'Australian Dollar' FROM DUAL UNION ALL
SELECT 7, N'AZM', N'Azerbaijanian Manat' FROM DUAL UNION ALL
SELECT 8, N'BSD', N'Bahamian Dollar' FROM DUAL UNION ALL
SELECT 9, N'BHD', N'Bahraini Dinar' FROM DUAL UNION ALL
SELECT 10, N'THB', N'Baht' FROM DUAL UNION ALL
SELECT 11, N'PAB', N'Balboa' FROM DUAL UNION ALL
SELECT 12, N'BBD', N'Barbados Dollar' FROM DUAL UNION ALL
SELECT 13, N'BEF', N'Belgian Franc' FROM DUAL UNION ALL
SELECT 14, N'VEB', N'Bolivar' FROM DUAL UNION ALL
SELECT 15, N'BOB', N'Boliviano' FROM DUAL UNION ALL
SELECT 16, N'BRL', N'Brazilian Real' FROM DUAL UNION ALL
SELECT 17, N'BND', N'Brunei Dollar' FROM DUAL UNION ALL
SELECT 18, N'BGN', N'Bulgarian Lev' FROM DUAL UNION ALL
SELECT 19, N'CAD', N'Canadian Dollar' FROM DUAL UNION ALL
SELECT 20, N'GHC', N'Cedi' FROM DUAL UNION ALL
SELECT 21, N'XOF', N'CFA Franc BCEAO' FROM DUAL UNION ALL
SELECT 22, N'CLP', N'Chilean Peso' FROM DUAL UNION ALL
SELECT 23, N'COP', N'Colombian Peso' FROM DUAL UNION ALL
SELECT 24, N'CRC', N'Costa Rican Colon' FROM DUAL UNION ALL
SELECT 25, N'HRK', N'Croatian Kuna' FROM DUAL UNION ALL
SELECT 26, N'CYP', N'Cyprus Pound' FROM DUAL UNION ALL
SELECT 27, N'CZK', N'Czech Koruna' FROM DUAL UNION ALL
SELECT 28, N'DKK', N'Danish Krone' FROM DUAL UNION ALL
SELECT 29, N'DEM', N'Deutsche Mark' FROM DUAL UNION ALL
SELECT 30, N'DOP', N'Dominican Peso' FROM DUAL UNION ALL
SELECT 31, N'VND', N'Dong' FROM DUAL UNION ALL
SELECT 32, N'GRD', N'Drachma' FROM DUAL UNION ALL
SELECT 33, N'EGP', N'Egyptian Pound' FROM DUAL UNION ALL
SELECT 34, N'SVC', N'El Salvador Colon' FROM DUAL UNION ALL
SELECT 35, N'AED', N'Emirati Dirham' FROM DUAL UNION ALL
SELECT 36, N'EUR', N'EURO' FROM DUAL UNION ALL
SELECT 37, N'FJD', N'Fiji Dollar' FROM DUAL UNION ALL
SELECT 38, N'HUF', N'Forint' FROM DUAL UNION ALL
SELECT 39, N'FRF', N'French Franc' FROM DUAL UNION ALL
SELECT 40, N'PYG', N'Guarani' FROM DUAL UNION ALL
SELECT 41, N'HKD', N'Hong Kong Dollar' FROM DUAL UNION ALL
SELECT 42, N'ISK', N'Iceland Krona' FROM DUAL UNION ALL
SELECT 43, N'INR', N'Indian Rupee' FROM DUAL UNION ALL
SELECT 44, N'IEP', N'Irish Pound' FROM DUAL UNION ALL
SELECT 45, N'ITL', N'Italian Lira' FROM DUAL UNION ALL
SELECT 46, N'JMD', N'Jamaican Dollar' FROM DUAL UNION ALL
SELECT 47, N'JOD', N'Jordanian Dinar' FROM DUAL UNION ALL
SELECT 48, N'KES', N'Kenyan Shilling' FROM DUAL UNION ALL
SELECT 49, N'EEK', N'Kroon' FROM DUAL UNION ALL
SELECT 50, N'KWD', N'Kuwaiti Dinar' FROM DUAL UNION ALL
SELECT 51, N'AOA', N'Kwanza' FROM DUAL UNION ALL
SELECT 52, N'LVL', N'Latvian Lats' FROM DUAL UNION ALL
SELECT 53, N'LBP', N'Lebanese Pound' FROM DUAL UNION ALL
SELECT 54, N'ALL', N'Lek' FROM DUAL UNION ALL
SELECT 55, N'ROL', N'Leu' FROM DUAL UNION ALL
SELECT 56, N'LTL', N'Lithuanian Litas' FROM DUAL UNION ALL
SELECT 57, N'MYR', N'Malaysian Ringgit' FROM DUAL UNION ALL
SELECT 58, N'MTL', N'Maltese Lira' FROM DUAL UNION ALL
SELECT 59, N'FIM', N'Markka' FROM DUAL UNION ALL
SELECT 60, N'MUR', N'Mauritius Rupee' FROM DUAL UNION ALL
SELECT 61, N'MXN', N'Mexican Peso' FROM DUAL UNION ALL
SELECT 62, N'MAD', N'Moroccan Dirham' FROM DUAL UNION ALL
SELECT 63, N'NGN', N'Naira' FROM DUAL UNION ALL
SELECT 64, N'NAD', N'Namibia Dollar' FROM DUAL UNION ALL
SELECT 65, N'NPR', N'Nepalese Rupee' FROM DUAL UNION ALL
SELECT 66, N'ANG', N'Netherlands Antillian Guilder' FROM DUAL UNION ALL
SELECT 67, N'NLG', N'Netherlands Guilder' FROM DUAL UNION ALL
SELECT 68, N'ILS', N'New Israeli Shekel' FROM DUAL UNION ALL
SELECT 69, N'TWD', N'New Taiwan Dollar' FROM DUAL UNION ALL
SELECT 70, N'NZD', N'New Zealand Dollar' FROM DUAL UNION ALL
SELECT 71, N'BTN', N'Ngultrum' FROM DUAL UNION ALL
SELECT 72, N'NOK', N'Norwegian Krone' FROM DUAL UNION ALL
SELECT 73, N'PEN', N'Nuevo Sol' FROM DUAL UNION ALL
SELECT 74, N'OMR', N'Omani Rial' FROM DUAL UNION ALL
SELECT 75, N'PKR', N'Pakistan Rupee' FROM DUAL UNION ALL
SELECT 76, N'PHP', N'Philippine Peso' FROM DUAL UNION ALL
SELECT 77, N'PLZ', N'Polish Zloty(old)' FROM DUAL UNION ALL
SELECT 78, N'PTE', N'Portuguese Escudo' FROM DUAL UNION ALL
SELECT 79, N'GTQ', N'Quetzal' FROM DUAL UNION ALL
SELECT 80, N'ZAR', N'Rand' FROM DUAL UNION ALL
SELECT 81, N'MVR', N'Rufiyaa' FROM DUAL UNION ALL
SELECT 82, N'IDR', N'Rupiah' FROM DUAL UNION ALL
SELECT 83, N'RUB', N'Russian Ruble' FROM DUAL UNION ALL
SELECT 84, N'RUR', N'Russian Ruble(old)' FROM DUAL UNION ALL
SELECT 85, N'SAR', N'Saudi Riyal' FROM DUAL UNION ALL
SELECT 86, N'ATS', N'Shilling' FROM DUAL UNION ALL
SELECT 87, N'SGD', N'Singapore Dollar' FROM DUAL UNION ALL
SELECT 88, N'SKK', N'Slovak Koruna' FROM DUAL UNION ALL
SELECT 89, N'ESP', N'Spanish Peseta' FROM DUAL UNION ALL
SELECT 90, N'LKR', N'Sri Lankan Rupee' FROM DUAL UNION ALL
SELECT 91, N'SEK', N'Swedish Krona' FROM DUAL UNION ALL
SELECT 92, N'CHF', N'Swiss Franc' FROM DUAL UNION ALL
SELECT 93, N'BDT', N'Taka' FROM DUAL UNION ALL
SELECT 94, N'SIT', N'Tolar' FROM DUAL UNION ALL
SELECT 95, N'TTD', N'Trinidad and Tobago Dollar' FROM DUAL UNION ALL
SELECT 96, N'TND', N'Tunisian Dinar' FROM DUAL UNION ALL
SELECT 97, N'TRL', N'Turkish Lira' FROM DUAL UNION ALL
SELECT 98, N'GBP', N'United Kingdom Pound' FROM DUAL UNION ALL
SELECT 99, N'UYU', N'Uruguayan Peso' FROM DUAL UNION ALL
SELECT 100, N'USD', N'US Dollar' FROM DUAL UNION ALL
SELECT 101, N'KRW', N'Won' FROM DUAL UNION ALL
SELECT 102, N'JPY', N'Yen' FROM DUAL UNION ALL
SELECT 103, N'CNY', N'Yuan Renminbi' FROM DUAL UNION ALL
SELECT 104, N'ZWD', N'Zimbabwe Dollar' FROM DUAL UNION ALL
SELECT 105, N'PLN', N'Zloty' FROM DUAL;

COMMIT;