-- Schema creation script for OT user
-- This script assumes the OT user has already been created by the container

-- Connect as OT user (the container will run this as the APP_USER)
-- Create tables

-- regions
CREATE TABLE regions 
(
    region_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    region_name VARCHAR2( 50 ) NOT NULL,
    PRIMARY KEY(region_id)
);

-- countries table
CREATE TABLE countries 
(
    country_id CHAR( 2 ) PRIMARY KEY,
    country_name VARCHAR2( 40 ) NOT NULL,
    region_id NUMBER,
    CONSTRAINT fk_countries_regions FOREIGN KEY( region_id )
        REFERENCES regions( region_id ) 
        ON DELETE CASCADE
);

-- locations
CREATE TABLE locations
(
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR2( 255 ) NOT NULL,
    postal_code VARCHAR2( 20 ),
    city VARCHAR2( 50 ),
    state VARCHAR2( 50 ),
    country_id CHAR( 2 ),
    PRIMARY KEY(location_id),
    CONSTRAINT fk_locations_countries 
        FOREIGN KEY( country_id )
        REFERENCES countries( country_id ) 
        ON DELETE CASCADE
);

-- warehouses
CREATE TABLE warehouses
(
    warehouse_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    warehouse_name VARCHAR( 255 ),
    location_id NUMBER( 12, 0 ),
    PRIMARY KEY(warehouse_id),
    CONSTRAINT fk_warehouses_locations 
        FOREIGN KEY( location_id )
        REFERENCES locations( location_id ) 
        ON DELETE CASCADE
);

-- employees
CREATE TABLE employees
(
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR( 255 ) NOT NULL,
    last_name VARCHAR( 255 ) NOT NULL,
    email VARCHAR( 255 ) NOT NULL,
    phone VARCHAR( 50 ) NOT NULL ,
    hire_date DATE NOT NULL,
    manager_id NUMBER( 12, 0 ),
    job_title VARCHAR( 255 ) NOT NULL,
    PRIMARY KEY(employee_id),
    CONSTRAINT fk_employees_manager 
        FOREIGN KEY( manager_id )
        REFERENCES employees( employee_id )
        ON DELETE CASCADE
);

-- product categories
CREATE TABLE product_categories
(
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2( 255 ) NOT NULL,
    PRIMARY KEY(category_id)
);

-- products table
CREATE TABLE products
(
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR2( 255 ) NOT NULL,
    description VARCHAR2( 2000 ),
    standard_cost NUMBER( 9, 2 ),
    list_price NUMBER( 9, 2 ),
    category_id NUMBER NOT NULL,
    PRIMARY KEY(product_id),
    CONSTRAINT fk_products_categories 
        FOREIGN KEY( category_id )
        REFERENCES product_categories( category_id ) 
        ON DELETE CASCADE
);

-- customers
CREATE TABLE customers
(
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2( 255 ) NOT NULL,
    address VARCHAR2( 255 ),
    website VARCHAR2( 255 ),
    credit_limit NUMBER( 8, 2 ),
    PRIMARY KEY(customer_id)
);

-- contacts
CREATE TABLE contacts
(
    contact_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2( 255 ) NOT NULL,
    last_name VARCHAR2( 255 ) NOT NULL,
    email VARCHAR2( 255 ) NOT NULL,
    phone VARCHAR2( 20 ),
    customer_id NUMBER,
    PRIMARY KEY(contact_id),
    CONSTRAINT fk_contacts_customers 
        FOREIGN KEY( customer_id )
        REFERENCES customers( customer_id ) 
        ON DELETE CASCADE
);

-- orders table
CREATE TABLE orders
(
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id NUMBER( 6, 0 ) NOT NULL,
    status VARCHAR( 20 ) NOT NULL,
    salesman_id NUMBER( 6, 0 ),
    order_date DATE NOT NULL,
    PRIMARY KEY(order_id),
    CONSTRAINT fk_orders_customers 
        FOREIGN KEY( customer_id )
        REFERENCES customers( customer_id )
        ON DELETE CASCADE,
    CONSTRAINT fk_orders_employees 
        FOREIGN KEY( salesman_id )
        REFERENCES employees( employee_id ) 
        ON DELETE SET NULL
);

-- order items
CREATE TABLE order_items
(
    order_id NUMBER( 12, 0 ),
    item_id NUMBER( 12, 0 ),
    product_id NUMBER( 12, 0 ) NOT NULL,
    quantity NUMBER( 8, 2 ) NOT NULL,
    unit_price NUMBER( 8, 2 ) NOT NULL,
    PRIMARY KEY(order_id, item_id),
    CONSTRAINT fk_order_items_products 
        FOREIGN KEY( product_id )
        REFERENCES products( product_id ) 
        ON DELETE CASCADE,
    CONSTRAINT fk_order_items_orders 
        FOREIGN KEY( order_id )
        REFERENCES orders( order_id ) 
        ON DELETE CASCADE
);

-- inventories
CREATE TABLE inventories
(
    product_id NUMBER( 12, 0 ),
    warehouse_id NUMBER( 12, 0 ),
    quantity NUMBER( 8, 0 ) NOT NULL,
    PRIMARY KEY(product_id, warehouse_id),
    CONSTRAINT fk_inventories_products 
        FOREIGN KEY( product_id )
        REFERENCES products( product_id ) 
        ON DELETE CASCADE,
    CONSTRAINT fk_inventories_warehouses 
        FOREIGN KEY( warehouse_id )
        REFERENCES warehouses( warehouse_id ) 
        ON DELETE CASCADE
);