// This code was generated by `SqlHydra.SqlServer` -- v4.1.0-beta.2.
namespace SqlServer.AdventureWorksNet9

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 1, 0)
    let ns = "SqlServer.AdventureWorksNet9"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module HumanResources =

    [<CLIMutable>]
    type Department =
        { [<ProviderDbType("SmallInt")>]
          DepartmentID: int16
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("NVarChar")>]
          GroupName: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Department = table<Department>

    [<CLIMutable>]
    type Employee =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("NVarChar")>]
          NationalIDNumber: string
          [<ProviderDbType("NVarChar")>]
          LoginID: string
          [<ProviderDbType("SqlHierarchyId")>]
          OrganizationNode: Option<Microsoft.SqlServer.Types.SqlHierarchyId>
          [<ProviderDbType("SmallInt")>]
          OrganizationLevel: Option<int16>
          [<ProviderDbType("NVarChar")>]
          JobTitle: string
          [<ProviderDbType("Date")>]
          BirthDate: System.DateOnly
          [<ProviderDbType("NChar")>]
          MaritalStatus: string
          [<ProviderDbType("NChar")>]
          Gender: string
          [<ProviderDbType("Date")>]
          HireDate: System.DateOnly
          [<ProviderDbType("Bit")>]
          SalariedFlag: bool
          [<ProviderDbType("SmallInt")>]
          VacationHours: int16
          [<ProviderDbType("SmallInt")>]
          SickLeaveHours: int16
          [<ProviderDbType("Bit")>]
          CurrentFlag: bool
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Employee = table<Employee>

    [<CLIMutable>]
    type EmployeeDepartmentHistory =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("SmallInt")>]
          DepartmentID: int16
          [<ProviderDbType("TinyInt")>]
          ShiftID: byte
          [<ProviderDbType("Date")>]
          StartDate: System.DateOnly
          [<ProviderDbType("Date")>]
          EndDate: Option<System.DateOnly>
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let EmployeeDepartmentHistory = table<EmployeeDepartmentHistory>

    [<CLIMutable>]
    type EmployeePayHistory =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("DateTime")>]
          RateChangeDate: System.DateTime
          [<ProviderDbType("Money")>]
          Rate: decimal
          [<ProviderDbType("TinyInt")>]
          PayFrequency: byte
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let EmployeePayHistory = table<EmployeePayHistory>

    [<CLIMutable>]
    type JobCandidate =
        { [<ProviderDbType("Int")>]
          JobCandidateID: int
          [<ProviderDbType("Int")>]
          BusinessEntityID: Option<int>
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let JobCandidate = table<JobCandidate>

    [<CLIMutable>]
    type Shift =
        { [<ProviderDbType("TinyInt")>]
          ShiftID: byte
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("Time")>]
          StartTime: System.TimeOnly
          [<ProviderDbType("Time")>]
          EndTime: System.TimeOnly
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Shift = table<Shift>

module Person =

    [<CLIMutable>]
    type Address =
        { [<ProviderDbType("Int")>]
          AddressID: int
          [<ProviderDbType("NVarChar")>]
          AddressLine1: string
          [<ProviderDbType("NVarChar")>]
          AddressLine2: Option<string>
          [<ProviderDbType("NVarChar")>]
          City: string
          [<ProviderDbType("Int")>]
          StateProvinceID: int
          [<ProviderDbType("NVarChar")>]
          PostalCode: string
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Address = table<Address>

    [<CLIMutable>]
    type AddressType =
        { [<ProviderDbType("Int")>]
          AddressTypeID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let AddressType = table<AddressType>

    [<CLIMutable>]
    type BusinessEntity =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let BusinessEntity = table<BusinessEntity>

    [<CLIMutable>]
    type BusinessEntityAddress =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("Int")>]
          AddressID: int
          [<ProviderDbType("Int")>]
          AddressTypeID: int
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let BusinessEntityAddress = table<BusinessEntityAddress>

    [<CLIMutable>]
    type BusinessEntityContact =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("Int")>]
          PersonID: int
          [<ProviderDbType("Int")>]
          ContactTypeID: int
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let BusinessEntityContact = table<BusinessEntityContact>

    [<CLIMutable>]
    type ContactType =
        { [<ProviderDbType("Int")>]
          ContactTypeID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ContactType = table<ContactType>

    [<CLIMutable>]
    type CountryRegion =
        { [<ProviderDbType("NVarChar")>]
          CountryRegionCode: string
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let CountryRegion = table<CountryRegion>

    [<CLIMutable>]
    type EmailAddress =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("Int")>]
          EmailAddressID: int
          [<ProviderDbType("NVarChar")>]
          EmailAddress: Option<string>
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let EmailAddress = table<EmailAddress>

    [<CLIMutable>]
    type Password =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("VarChar")>]
          PasswordHash: string
          [<ProviderDbType("VarChar")>]
          PasswordSalt: string
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Password = table<Password>

    [<CLIMutable>]
    type Person =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("NChar")>]
          PersonType: string
          [<ProviderDbType("Bit")>]
          NameStyle: bool
          [<ProviderDbType("NVarChar")>]
          Title: Option<string>
          [<ProviderDbType("NVarChar")>]
          FirstName: string
          [<ProviderDbType("NVarChar")>]
          MiddleName: Option<string>
          [<ProviderDbType("NVarChar")>]
          LastName: string
          [<ProviderDbType("NVarChar")>]
          Suffix: Option<string>
          [<ProviderDbType("Int")>]
          EmailPromotion: int
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Person = table<Person>

    [<CLIMutable>]
    type PersonPhone =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("NVarChar")>]
          PhoneNumber: string
          [<ProviderDbType("Int")>]
          PhoneNumberTypeID: int
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let PersonPhone = table<PersonPhone>

    [<CLIMutable>]
    type PhoneNumberType =
        { [<ProviderDbType("Int")>]
          PhoneNumberTypeID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let PhoneNumberType = table<PhoneNumberType>

    [<CLIMutable>]
    type StateProvince =
        { [<ProviderDbType("Int")>]
          StateProvinceID: int
          [<ProviderDbType("NChar")>]
          StateProvinceCode: string
          [<ProviderDbType("NVarChar")>]
          CountryRegionCode: string
          [<ProviderDbType("Bit")>]
          IsOnlyStateProvinceFlag: bool
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("Int")>]
          TerritoryID: int
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let StateProvince = table<StateProvince>

module Production =

    [<CLIMutable>]
    type BillOfMaterials =
        { [<ProviderDbType("Int")>]
          BillOfMaterialsID: int
          [<ProviderDbType("Int")>]
          ProductAssemblyID: Option<int>
          [<ProviderDbType("Int")>]
          ComponentID: int
          [<ProviderDbType("DateTime")>]
          StartDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          EndDate: Option<System.DateTime>
          [<ProviderDbType("NChar")>]
          UnitMeasureCode: string
          [<ProviderDbType("SmallInt")>]
          BOMLevel: int16
          [<ProviderDbType("Decimal")>]
          PerAssemblyQty: decimal
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let BillOfMaterials = table<BillOfMaterials>

    [<CLIMutable>]
    type Culture =
        { [<ProviderDbType("NChar")>]
          CultureID: string
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Culture = table<Culture>

    [<CLIMutable>]
    type Document =
        { [<ProviderDbType("SqlHierarchyId")>]
          DocumentNode: Microsoft.SqlServer.Types.SqlHierarchyId
          [<ProviderDbType("SmallInt")>]
          DocumentLevel: Option<int16>
          [<ProviderDbType("NVarChar")>]
          Title: string
          [<ProviderDbType("Int")>]
          Owner: int
          [<ProviderDbType("Bit")>]
          FolderFlag: bool
          [<ProviderDbType("NVarChar")>]
          FileName: string
          [<ProviderDbType("NVarChar")>]
          FileExtension: string
          [<ProviderDbType("NChar")>]
          Revision: string
          [<ProviderDbType("Int")>]
          ChangeNumber: int
          [<ProviderDbType("TinyInt")>]
          Status: byte
          [<ProviderDbType("NVarChar")>]
          DocumentSummary: Option<string>
          [<ProviderDbType("VarBinary")>]
          Document: Option<byte[]>
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Document = table<Document>

    [<CLIMutable>]
    type Illustration =
        { [<ProviderDbType("Int")>]
          IllustrationID: int
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Illustration = table<Illustration>

    [<CLIMutable>]
    type Location =
        { [<ProviderDbType("SmallInt")>]
          LocationID: int16
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("SmallMoney")>]
          CostRate: decimal
          [<ProviderDbType("Decimal")>]
          Availability: decimal
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Location = table<Location>

    [<CLIMutable>]
    type Product =
        { [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("NVarChar")>]
          ProductNumber: string
          [<ProviderDbType("Bit")>]
          MakeFlag: bool
          [<ProviderDbType("Bit")>]
          FinishedGoodsFlag: bool
          [<ProviderDbType("NVarChar")>]
          Color: Option<string>
          [<ProviderDbType("SmallInt")>]
          SafetyStockLevel: int16
          [<ProviderDbType("SmallInt")>]
          ReorderPoint: int16
          [<ProviderDbType("Money")>]
          StandardCost: decimal
          [<ProviderDbType("Money")>]
          ListPrice: decimal
          [<ProviderDbType("NVarChar")>]
          Size: Option<string>
          [<ProviderDbType("NChar")>]
          SizeUnitMeasureCode: Option<string>
          [<ProviderDbType("NChar")>]
          WeightUnitMeasureCode: Option<string>
          [<ProviderDbType("Decimal")>]
          Weight: Option<decimal>
          [<ProviderDbType("Int")>]
          DaysToManufacture: int
          [<ProviderDbType("NChar")>]
          ProductLine: Option<string>
          [<ProviderDbType("NChar")>]
          Class: Option<string>
          [<ProviderDbType("NChar")>]
          Style: Option<string>
          [<ProviderDbType("Int")>]
          ProductSubcategoryID: Option<int>
          [<ProviderDbType("Int")>]
          ProductModelID: Option<int>
          [<ProviderDbType("DateTime")>]
          SellStartDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          SellEndDate: Option<System.DateTime>
          [<ProviderDbType("DateTime")>]
          DiscontinuedDate: Option<System.DateTime>
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Product = table<Product>

    [<CLIMutable>]
    type ProductCategory =
        { [<ProviderDbType("Int")>]
          ProductCategoryID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductCategory = table<ProductCategory>

    [<CLIMutable>]
    type ProductCostHistory =
        { [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("DateTime")>]
          StartDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          EndDate: Option<System.DateTime>
          [<ProviderDbType("Money")>]
          StandardCost: decimal
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductCostHistory = table<ProductCostHistory>

    [<CLIMutable>]
    type ProductDescription =
        { [<ProviderDbType("Int")>]
          ProductDescriptionID: int
          [<ProviderDbType("NVarChar")>]
          Description: string
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductDescription = table<ProductDescription>

    [<CLIMutable>]
    type ProductDocument =
        { [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("SqlHierarchyId")>]
          DocumentNode: Microsoft.SqlServer.Types.SqlHierarchyId
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductDocument = table<ProductDocument>

    [<CLIMutable>]
    type ProductInventory =
        { [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("SmallInt")>]
          LocationID: int16
          [<ProviderDbType("NVarChar")>]
          Shelf: string
          [<ProviderDbType("TinyInt")>]
          Bin: byte
          [<ProviderDbType("SmallInt")>]
          Quantity: int16
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductInventory = table<ProductInventory>

    [<CLIMutable>]
    type ProductListPriceHistory =
        { [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("DateTime")>]
          StartDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          EndDate: Option<System.DateTime>
          [<ProviderDbType("Money")>]
          ListPrice: decimal
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductListPriceHistory = table<ProductListPriceHistory>

    [<CLIMutable>]
    type ProductModel =
        { [<ProviderDbType("Int")>]
          ProductModelID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductModel = table<ProductModel>

    [<CLIMutable>]
    type ProductModelIllustration =
        { [<ProviderDbType("Int")>]
          ProductModelID: int
          [<ProviderDbType("Int")>]
          IllustrationID: int
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductModelIllustration = table<ProductModelIllustration>

    [<CLIMutable>]
    type ProductModelProductDescriptionCulture =
        { [<ProviderDbType("Int")>]
          ProductModelID: int
          [<ProviderDbType("Int")>]
          ProductDescriptionID: int
          [<ProviderDbType("NChar")>]
          CultureID: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductModelProductDescriptionCulture =
        table<ProductModelProductDescriptionCulture>

    [<CLIMutable>]
    type ProductPhoto =
        { [<ProviderDbType("Int")>]
          ProductPhotoID: int
          [<ProviderDbType("VarBinary")>]
          ThumbNailPhoto: Option<byte[]>
          [<ProviderDbType("NVarChar")>]
          ThumbnailPhotoFileName: Option<string>
          [<ProviderDbType("VarBinary")>]
          LargePhoto: Option<byte[]>
          [<ProviderDbType("NVarChar")>]
          LargePhotoFileName: Option<string>
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductPhoto = table<ProductPhoto>

    [<CLIMutable>]
    type ProductProductPhoto =
        { [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("Int")>]
          ProductPhotoID: int
          [<ProviderDbType("Bit")>]
          Primary: bool
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductProductPhoto = table<ProductProductPhoto>

    [<CLIMutable>]
    type ProductReview =
        { [<ProviderDbType("Int")>]
          ProductReviewID: int
          [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("NVarChar")>]
          ReviewerName: string
          [<ProviderDbType("DateTime")>]
          ReviewDate: System.DateTime
          [<ProviderDbType("NVarChar")>]
          EmailAddress: string
          [<ProviderDbType("Int")>]
          Rating: int
          [<ProviderDbType("NVarChar")>]
          Comments: Option<string>
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductReview = table<ProductReview>

    [<CLIMutable>]
    type ProductSubcategory =
        { [<ProviderDbType("Int")>]
          ProductSubcategoryID: int
          [<ProviderDbType("Int")>]
          ProductCategoryID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductSubcategory = table<ProductSubcategory>

    [<CLIMutable>]
    type ScrapReason =
        { [<ProviderDbType("SmallInt")>]
          ScrapReasonID: int16
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ScrapReason = table<ScrapReason>

    [<CLIMutable>]
    type TransactionHistory =
        { [<ProviderDbType("Int")>]
          TransactionID: int
          [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("Int")>]
          ReferenceOrderID: int
          [<ProviderDbType("Int")>]
          ReferenceOrderLineID: int
          [<ProviderDbType("DateTime")>]
          TransactionDate: System.DateTime
          [<ProviderDbType("NChar")>]
          TransactionType: string
          [<ProviderDbType("Int")>]
          Quantity: int
          [<ProviderDbType("Money")>]
          ActualCost: decimal
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let TransactionHistory = table<TransactionHistory>

    [<CLIMutable>]
    type TransactionHistoryArchive =
        { [<ProviderDbType("Int")>]
          TransactionID: int
          [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("Int")>]
          ReferenceOrderID: int
          [<ProviderDbType("Int")>]
          ReferenceOrderLineID: int
          [<ProviderDbType("DateTime")>]
          TransactionDate: System.DateTime
          [<ProviderDbType("NChar")>]
          TransactionType: string
          [<ProviderDbType("Int")>]
          Quantity: int
          [<ProviderDbType("Money")>]
          ActualCost: decimal
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let TransactionHistoryArchive = table<TransactionHistoryArchive>

    [<CLIMutable>]
    type UnitMeasure =
        { [<ProviderDbType("NChar")>]
          UnitMeasureCode: string
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let UnitMeasure = table<UnitMeasure>

    [<CLIMutable>]
    type WorkOrder =
        { [<ProviderDbType("Int")>]
          WorkOrderID: int
          [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("Int")>]
          OrderQty: int
          [<ProviderDbType("Int")>]
          StockedQty: int
          [<ProviderDbType("SmallInt")>]
          ScrappedQty: int16
          [<ProviderDbType("DateTime")>]
          StartDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          EndDate: Option<System.DateTime>
          [<ProviderDbType("DateTime")>]
          DueDate: System.DateTime
          [<ProviderDbType("SmallInt")>]
          ScrapReasonID: Option<int16>
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let WorkOrder = table<WorkOrder>

    [<CLIMutable>]
    type WorkOrderRouting =
        { [<ProviderDbType("Int")>]
          WorkOrderID: int
          [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("SmallInt")>]
          OperationSequence: int16
          [<ProviderDbType("SmallInt")>]
          LocationID: int16
          [<ProviderDbType("DateTime")>]
          ScheduledStartDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          ScheduledEndDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          ActualStartDate: Option<System.DateTime>
          [<ProviderDbType("DateTime")>]
          ActualEndDate: Option<System.DateTime>
          [<ProviderDbType("Decimal")>]
          ActualResourceHrs: Option<decimal>
          [<ProviderDbType("Money")>]
          PlannedCost: decimal
          [<ProviderDbType("Money")>]
          ActualCost: Option<decimal>
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let WorkOrderRouting = table<WorkOrderRouting>

module Purchasing =

    [<CLIMutable>]
    type ProductVendor =
        { [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("Int")>]
          AverageLeadTime: int
          [<ProviderDbType("Money")>]
          StandardPrice: decimal
          [<ProviderDbType("Money")>]
          LastReceiptCost: Option<decimal>
          [<ProviderDbType("DateTime")>]
          LastReceiptDate: Option<System.DateTime>
          [<ProviderDbType("Int")>]
          MinOrderQty: int
          [<ProviderDbType("Int")>]
          MaxOrderQty: int
          [<ProviderDbType("Int")>]
          OnOrderQty: Option<int>
          [<ProviderDbType("NChar")>]
          UnitMeasureCode: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ProductVendor = table<ProductVendor>

    [<CLIMutable>]
    type PurchaseOrderDetail =
        { [<ProviderDbType("Int")>]
          PurchaseOrderID: int
          [<ProviderDbType("Int")>]
          PurchaseOrderDetailID: int
          [<ProviderDbType("DateTime")>]
          DueDate: System.DateTime
          [<ProviderDbType("SmallInt")>]
          OrderQty: int16
          [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("Money")>]
          UnitPrice: decimal
          [<ProviderDbType("Money")>]
          LineTotal: decimal
          [<ProviderDbType("Decimal")>]
          ReceivedQty: decimal
          [<ProviderDbType("Decimal")>]
          RejectedQty: decimal
          [<ProviderDbType("Decimal")>]
          StockedQty: decimal
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let PurchaseOrderDetail = table<PurchaseOrderDetail>

    [<CLIMutable>]
    type PurchaseOrderHeader =
        { [<ProviderDbType("Int")>]
          PurchaseOrderID: int
          [<ProviderDbType("TinyInt")>]
          RevisionNumber: byte
          [<ProviderDbType("TinyInt")>]
          Status: byte
          [<ProviderDbType("Int")>]
          EmployeeID: int
          [<ProviderDbType("Int")>]
          VendorID: int
          [<ProviderDbType("Int")>]
          ShipMethodID: int
          [<ProviderDbType("DateTime")>]
          OrderDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          ShipDate: Option<System.DateTime>
          [<ProviderDbType("Money")>]
          SubTotal: decimal
          [<ProviderDbType("Money")>]
          TaxAmt: decimal
          [<ProviderDbType("Money")>]
          Freight: decimal
          [<ProviderDbType("Money")>]
          TotalDue: decimal
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let PurchaseOrderHeader = table<PurchaseOrderHeader>

    [<CLIMutable>]
    type ShipMethod =
        { [<ProviderDbType("Int")>]
          ShipMethodID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("Money")>]
          ShipBase: decimal
          [<ProviderDbType("Money")>]
          ShipRate: decimal
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ShipMethod = table<ShipMethod>

    [<CLIMutable>]
    type Vendor =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("NVarChar")>]
          AccountNumber: string
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("TinyInt")>]
          CreditRating: byte
          [<ProviderDbType("Bit")>]
          PreferredVendorStatus: bool
          [<ProviderDbType("Bit")>]
          ActiveFlag: bool
          [<ProviderDbType("NVarChar")>]
          PurchasingWebServiceURL: Option<string>
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Vendor = table<Vendor>

module Sales =

    [<CLIMutable>]
    type CountryRegionCurrency =
        { [<ProviderDbType("NVarChar")>]
          CountryRegionCode: string
          [<ProviderDbType("NChar")>]
          CurrencyCode: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let CountryRegionCurrency = table<CountryRegionCurrency>

    [<CLIMutable>]
    type CreditCard =
        { [<ProviderDbType("Int")>]
          CreditCardID: int
          [<ProviderDbType("NVarChar")>]
          CardType: string
          [<ProviderDbType("NVarChar")>]
          CardNumber: string
          [<ProviderDbType("TinyInt")>]
          ExpMonth: byte
          [<ProviderDbType("SmallInt")>]
          ExpYear: int16
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let CreditCard = table<CreditCard>

    [<CLIMutable>]
    type Currency =
        { [<ProviderDbType("NChar")>]
          CurrencyCode: string
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Currency = table<Currency>

    [<CLIMutable>]
    type CurrencyRate =
        { [<ProviderDbType("Int")>]
          CurrencyRateID: int
          [<ProviderDbType("DateTime")>]
          CurrencyRateDate: System.DateTime
          [<ProviderDbType("NChar")>]
          FromCurrencyCode: string
          [<ProviderDbType("NChar")>]
          ToCurrencyCode: string
          [<ProviderDbType("Money")>]
          AverageRate: decimal
          [<ProviderDbType("Money")>]
          EndOfDayRate: decimal
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let CurrencyRate = table<CurrencyRate>

    [<CLIMutable>]
    type Customer =
        { [<ProviderDbType("Int")>]
          CustomerID: int
          [<ProviderDbType("Int")>]
          PersonID: Option<int>
          [<ProviderDbType("Int")>]
          StoreID: Option<int>
          [<ProviderDbType("Int")>]
          TerritoryID: Option<int>
          [<ProviderDbType("VarChar")>]
          AccountNumber: string
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Customer = table<Customer>

    [<CLIMutable>]
    type PersonCreditCard =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("Int")>]
          CreditCardID: int
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let PersonCreditCard = table<PersonCreditCard>

    [<CLIMutable>]
    type SalesOrderDetail =
        { [<ProviderDbType("Int")>]
          SalesOrderID: int
          [<ProviderDbType("Int")>]
          SalesOrderDetailID: int
          [<ProviderDbType("NVarChar")>]
          CarrierTrackingNumber: Option<string>
          [<ProviderDbType("SmallInt")>]
          OrderQty: int16
          [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("Int")>]
          SpecialOfferID: int
          [<ProviderDbType("Money")>]
          UnitPrice: decimal
          [<ProviderDbType("Money")>]
          UnitPriceDiscount: decimal
          [<ProviderDbType("Decimal")>]
          LineTotal: decimal
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SalesOrderDetail = table<SalesOrderDetail>

    [<CLIMutable>]
    type SalesOrderHeader =
        { [<ProviderDbType("Int")>]
          SalesOrderID: int
          [<ProviderDbType("TinyInt")>]
          RevisionNumber: byte
          [<ProviderDbType("DateTime")>]
          OrderDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          DueDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          ShipDate: Option<System.DateTime>
          [<ProviderDbType("TinyInt")>]
          Status: byte
          [<ProviderDbType("Bit")>]
          OnlineOrderFlag: bool
          [<ProviderDbType("NVarChar")>]
          SalesOrderNumber: string
          [<ProviderDbType("NVarChar")>]
          PurchaseOrderNumber: Option<string>
          [<ProviderDbType("NVarChar")>]
          AccountNumber: Option<string>
          [<ProviderDbType("Int")>]
          CustomerID: int
          [<ProviderDbType("Int")>]
          SalesPersonID: Option<int>
          [<ProviderDbType("Int")>]
          TerritoryID: Option<int>
          [<ProviderDbType("Int")>]
          BillToAddressID: int
          [<ProviderDbType("Int")>]
          ShipToAddressID: int
          [<ProviderDbType("Int")>]
          ShipMethodID: int
          [<ProviderDbType("Int")>]
          CreditCardID: Option<int>
          [<ProviderDbType("VarChar")>]
          CreditCardApprovalCode: Option<string>
          [<ProviderDbType("Int")>]
          CurrencyRateID: Option<int>
          [<ProviderDbType("Money")>]
          SubTotal: decimal
          [<ProviderDbType("Money")>]
          TaxAmt: decimal
          [<ProviderDbType("Money")>]
          Freight: decimal
          [<ProviderDbType("Money")>]
          TotalDue: decimal
          [<ProviderDbType("NVarChar")>]
          Comment: Option<string>
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SalesOrderHeader = table<SalesOrderHeader>

    [<CLIMutable>]
    type SalesOrderHeaderSalesReason =
        { [<ProviderDbType("Int")>]
          SalesOrderID: int
          [<ProviderDbType("Int")>]
          SalesReasonID: int
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SalesOrderHeaderSalesReason = table<SalesOrderHeaderSalesReason>

    [<CLIMutable>]
    type SalesPerson =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("Int")>]
          TerritoryID: Option<int>
          [<ProviderDbType("Money")>]
          SalesQuota: Option<decimal>
          [<ProviderDbType("Money")>]
          Bonus: decimal
          [<ProviderDbType("SmallMoney")>]
          CommissionPct: decimal
          [<ProviderDbType("Money")>]
          SalesYTD: decimal
          [<ProviderDbType("Money")>]
          SalesLastYear: decimal
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SalesPerson = table<SalesPerson>

    [<CLIMutable>]
    type SalesPersonQuotaHistory =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("DateTime")>]
          QuotaDate: System.DateTime
          [<ProviderDbType("Money")>]
          SalesQuota: decimal
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SalesPersonQuotaHistory = table<SalesPersonQuotaHistory>

    [<CLIMutable>]
    type SalesReason =
        { [<ProviderDbType("Int")>]
          SalesReasonID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("NVarChar")>]
          ReasonType: string
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SalesReason = table<SalesReason>

    [<CLIMutable>]
    type SalesTaxRate =
        { [<ProviderDbType("Int")>]
          SalesTaxRateID: int
          [<ProviderDbType("Int")>]
          StateProvinceID: int
          [<ProviderDbType("TinyInt")>]
          TaxType: byte
          [<ProviderDbType("SmallMoney")>]
          TaxRate: decimal
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SalesTaxRate = table<SalesTaxRate>

    [<CLIMutable>]
    type SalesTerritory =
        { [<ProviderDbType("Int")>]
          TerritoryID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("NVarChar")>]
          CountryRegionCode: string
          [<ProviderDbType("NVarChar")>]
          Group: string
          [<ProviderDbType("Money")>]
          SalesYTD: decimal
          [<ProviderDbType("Money")>]
          SalesLastYear: decimal
          [<ProviderDbType("Money")>]
          CostYTD: decimal
          [<ProviderDbType("Money")>]
          CostLastYear: decimal
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SalesTerritory = table<SalesTerritory>

    [<CLIMutable>]
    type SalesTerritoryHistory =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("Int")>]
          TerritoryID: int
          [<ProviderDbType("DateTime")>]
          StartDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          EndDate: Option<System.DateTime>
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SalesTerritoryHistory = table<SalesTerritoryHistory>

    [<CLIMutable>]
    type ShoppingCartItem =
        { [<ProviderDbType("Int")>]
          ShoppingCartItemID: int
          [<ProviderDbType("NVarChar")>]
          ShoppingCartID: string
          [<ProviderDbType("Int")>]
          Quantity: int
          [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("DateTime")>]
          DateCreated: System.DateTime
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let ShoppingCartItem = table<ShoppingCartItem>

    [<CLIMutable>]
    type SpecialOffer =
        { [<ProviderDbType("Int")>]
          SpecialOfferID: int
          [<ProviderDbType("NVarChar")>]
          Description: string
          [<ProviderDbType("SmallMoney")>]
          DiscountPct: decimal
          [<ProviderDbType("NVarChar")>]
          Type: string
          [<ProviderDbType("NVarChar")>]
          Category: string
          [<ProviderDbType("DateTime")>]
          StartDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          EndDate: System.DateTime
          [<ProviderDbType("Int")>]
          MinQty: int
          [<ProviderDbType("Int")>]
          MaxQty: Option<int>
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SpecialOffer = table<SpecialOffer>

    [<CLIMutable>]
    type SpecialOfferProduct =
        { [<ProviderDbType("Int")>]
          SpecialOfferID: int
          [<ProviderDbType("Int")>]
          ProductID: int
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let SpecialOfferProduct = table<SpecialOfferProduct>

    [<CLIMutable>]
    type Store =
        { [<ProviderDbType("Int")>]
          BusinessEntityID: int
          [<ProviderDbType("NVarChar")>]
          Name: string
          [<ProviderDbType("Int")>]
          SalesPersonID: Option<int>
          [<ProviderDbType("UniqueIdentifier")>]
          rowguid: System.Guid
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let Store = table<Store>

module dbo =

    [<CLIMutable>]
    type AWBuildVersion =
        { [<ProviderDbType("TinyInt")>]
          SystemInformationID: byte
          [<ProviderDbType("NVarChar")>]
          ``Database Version``: string
          [<ProviderDbType("DateTime")>]
          VersionDate: System.DateTime
          [<ProviderDbType("DateTime")>]
          ModifiedDate: System.DateTime }

    let AWBuildVersion = table<AWBuildVersion>

    [<CLIMutable>]
    type DatabaseLog =
        { [<ProviderDbType("Int")>]
          DatabaseLogID: int
          [<ProviderDbType("DateTime")>]
          PostTime: System.DateTime
          [<ProviderDbType("NVarChar")>]
          DatabaseUser: string
          [<ProviderDbType("NVarChar")>]
          Event: string
          [<ProviderDbType("NVarChar")>]
          Schema: Option<string>
          [<ProviderDbType("NVarChar")>]
          Object: Option<string>
          [<ProviderDbType("NVarChar")>]
          TSQL: string }

    let DatabaseLog = table<DatabaseLog>

    [<CLIMutable>]
    type ErrorLog =
        { [<ProviderDbType("Int")>]
          ErrorLogID: int
          [<ProviderDbType("DateTime")>]
          ErrorTime: System.DateTime
          [<ProviderDbType("NVarChar")>]
          UserName: string
          [<ProviderDbType("Int")>]
          ErrorNumber: int
          [<ProviderDbType("Int")>]
          ErrorSeverity: Option<int>
          [<ProviderDbType("Int")>]
          ErrorState: Option<int>
          [<ProviderDbType("NVarChar")>]
          ErrorProcedure: Option<string>
          [<ProviderDbType("Int")>]
          ErrorLine: Option<int>
          [<ProviderDbType("NVarChar")>]
          ErrorMessage: string }

    let ErrorLog = table<ErrorLog>

module ext =

    [<CLIMutable>]
    type DateTime2Support =
        { [<ProviderDbType("Int")>]
          ID: int
          [<ProviderDbType("DateTime")>]
          LessPrecision: System.DateTime
          [<ProviderDbType("DateTime2")>]
          MorePrecision: System.DateTime }

    let DateTime2Support = table<DateTime2Support>

    [<CLIMutable>]
    type GetIdGuidRepro =
        { [<ProviderDbType("UniqueIdentifier")>]
          Id: System.Guid
          [<ProviderDbType("NChar")>]
          EmailAddress: string }

    let GetIdGuidRepro = table<GetIdGuidRepro>

    [<CLIMutable>]
    type HierarchyIdSupport =
        { [<ProviderDbType("UniqueIdentifier")>]
          Id: System.Guid
          [<ProviderDbType("SqlHierarchyId")>]
          Hierarchy: Microsoft.SqlServer.Types.SqlHierarchyId }

    let HierarchyIdSupport = table<HierarchyIdSupport>

    [<CLIMutable>]
    type NullableKeyUpsert =
        { [<ProviderDbType("UniqueIdentifier")>]
          Key1: System.Guid
          [<ProviderDbType("NVarChar")>]
          Key2: Option<string>
          [<ProviderDbType("NVarChar")>]
          Value: string }

    let NullableKeyUpsert = table<NullableKeyUpsert>



type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqlServerEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.SqlClient.SqlConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
