// This code was generated by SqlHydra.Sqlite.
namespace SampleApp.AdventureWorks

module main =
    [<CLIMutable>]
    type ErrorLog =
        { ErrorLogID: int64
          ErrorTime: System.DateTime
          UserName: string
          ErrorNumber: int64
          ErrorSeverity: Option<int64>
          ErrorState: Option<int64>
          ErrorProcedure: Option<string>
          ErrorLine: Option<int64>
          ErrorMessage: string }

    type ErrorLogReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type BuildVersion =
        { SystemInformationID: int64
          ``Database Version``: string
          VersionDate: System.DateTime
          ModifiedDate: System.DateTime }

    type BuildVersionReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type Address =
        { AddressID: int64
          AddressLine1: string
          AddressLine2: Option<string>
          City: string
          StateProvince: string
          CountryRegion: string
          PostalCode: string
          rowguid: string
          ModifiedDate: System.DateTime }

    type AddressReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type Customer =
        { CustomerID: int64
          NameStyle: int64
          Title: Option<string>
          FirstName: string
          MiddleName: Option<string>
          LastName: string
          Suffix: Option<string>
          CompanyName: Option<string>
          SalesPerson: Option<string>
          EmailAddress: Option<string>
          Phone: Option<string>
          PasswordHash: string
          PasswordSalt: string
          rowguid: string
          ModifiedDate: System.DateTime }

    type CustomerReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type CustomerAddress =
        { CustomerID: int64
          AddressID: int64
          AddressType: string
          rowguid: string
          ModifiedDate: System.DateTime }

    type CustomerAddressReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type Product =
        { ProductID: int64
          Name: string
          ProductNumber: string
          Color: Option<string>
          StandardCost: int64
          ListPrice: int64
          Size: Option<string>
          Weight: Option<int64>
          ProductCategoryID: Option<int64>
          ProductModelID: Option<int64>
          SellStartDate: System.DateTime
          SellEndDate: Option<System.DateTime>
          DiscontinuedDate: Option<System.DateTime>
          ThumbNailPhoto: Option<byte []>
          ThumbnailPhotoFileName: Option<string>
          rowguid: string
          ModifiedDate: System.DateTime }

    type ProductReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type ProductCategory =
        { ProductCategoryID: int64
          ParentProductCategoryID: Option<int64>
          Name: string
          rowguid: string
          ModifiedDate: System.DateTime }

    type ProductCategoryReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type ProductDescription =
        { ProductDescriptionID: int64
          Description: string
          rowguid: string
          ModifiedDate: System.DateTime }

    type ProductDescriptionReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type ProductModel =
        { ProductModelID: int64
          Name: string
          CatalogDescription: Option<string>
          rowguid: string
          ModifiedDate: System.DateTime }

    type ProductModelReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type ProductModelProductDescription =
        { ProductModelID: int64
          ProductDescriptionID: int64
          Culture: string
          rowguid: string
          ModifiedDate: System.DateTime }

    type ProductModelProductDescriptionReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type SalesOrderDetail =
        { SalesOrderID: int64
          SalesOrderDetailID: obj
          OrderQty: int64
          ProductID: int64
          UnitPrice: int64
          UnitPriceDiscount: int64
          LineTotal: int64
          rowguid: string
          ModifiedDate: System.DateTime }

    type SalesOrderDetailReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"

    [<CLIMutable>]
    type SalesOrderHeader =
        { SalesOrderID: int64
          RevisionNumber: int64
          OrderDate: System.DateTime
          DueDate: System.DateTime
          ShipDate: Option<System.DateTime>
          Status: int64
          OnlineOrderFlag: int64
          SalesOrderNumber: string
          PurchaseOrderNumber: Option<int64>
          AccountNumber: Option<string>
          CustomerID: int64
          ShipToAddressID: Option<int>
          BillToAddressID: Option<int>
          ShipMethod: string
          CreditCardApprovalCode: Option<string>
          SubTotal: int64
          TaxAmt: int64
          Freight: int64
          TotalDue: int64
          Comment: Option<string>
          rowguid: string
          ModifiedDate: System.DateTime }

    type SalesOrderHeaderReader(reader: System.Data.IDataReader) =
        member val FirstName = "FirstName"
