[general]
connection = "Server=localhost,12019;Database=AdventureWorks;User=sa;Password=Password#123;TrustServerCertificate=True"
output = "AdventureWorks.fs"
namespace = "SampleApp.AdventureWorks"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
[readers]
reader_type = "Microsoft.Data.SqlClient.SqlDataReader"
[filters]
include = []
exclude = []
