module SqlHydra.SchemaTemplate

open Domain

let backticks = Fantomas.FCS.Syntax.PrettyNaming.NormalizeIdentifierBackticks
let newLine = "\n"

let versionModule (cfg: Config) (v: Version.InformationalVersion) = $"""
module Version =
    let cli = System.Version({v.Version.Major}, {v.Version.Minor}, {v.Version.Build})
    let ns = "%s{cfg.Namespace}"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns
"""

let mkEnum db schema enum = stringBuffer {
    let enumType =
        db.Enums
        |> List.find (fun e -> e.Schema = schema && e.Name = enum)

    let labels =
        enumType.Labels
        |> List.sortBy _.SortOrder

    $"type {backticks enumType.Name} ="
    indent {
        for label in labels do
            $"| {backticks label.Name} = {label.SortOrder}"
    }
}

let mkTable cfg db (table: Table) schema tableName columnName = stringBuffer {
    let tableType =
        db.Tables
        |> List.find (fun t -> t.Schema = schema && t.Name = table.Name)

    if cfg.IsCLIMutable then "[<CLIMutable>]"

    let tblName = tableName { NamingContext.Table = table; Column = None }
    $"type {backticks tblName} ="
    indent {
        "{"
        indent {
            for col in tableType.Columns do
                let baseType =
                    // Handles array types: "byte[]", "string[]", "int[]", "int []", "int array"
                    if col.TypeMapping.ClrType.EndsWith "[]" || col.TypeMapping.ClrType.EndsWith "array" then
                        let baseTypeNm = col.TypeMapping.ClrType.Split([| "[]"; " []"; " array" |], System.StringSplitOptions.RemoveEmptyEntries) |> Array.head
                        $"{baseTypeNm} []"
                    else
                        col.TypeMapping.ClrType

                let columnPropertyType =
                    if col.IsNullable then
                        match cfg.NullablePropertyType with
                        | NullablePropertyType.Option ->
                            $"Option<{baseType}>"
                        | NullablePropertyType.Nullable ->
                            if col.TypeMapping.IsValueType()
                            then $"System.Nullable<{baseType}>"
                            else baseType
                    else
                        baseType

                let providerDbTypeAttribute =
                    match col.TypeMapping.ProviderDbType with
                    | Some providerDbType when cfg.ProviderDbTypeAttributes ->
                        Some $"[<ProviderDbType(\"{providerDbType}\")>]"
                    | _ ->
                        None

                if providerDbTypeAttribute.IsSome then providerDbTypeAttribute.Value
                let colName = columnName { NamingContext.Table = table; Column = Some col }
                $"""{if cfg.IsMutableProperties then "mutable " else ""}{backticks colName}: {columnPropertyType}"""
        }
        "}"
    }
}

let generate (cfg: Config) (provider: ISqlHydraDbProvider) (db: Schema) (version: Version.InformationalVersion) (namingExtensions: IExtendNaming list) = stringBuffer {
    let tableName =
        let baseFn (ctx: NamingContext) = ctx.Table.Name
        namingExtensions |> List.fold (fun acc ext -> ext.ExtendTableName acc) baseFn

    let columnName =
        let baseFn (ctx: NamingContext) = ctx.Column.Value.Name
        namingExtensions |> List.fold (fun acc ext -> ext.ExtendColumnName acc) baseFn

    let filteredTables =
        db.Tables
        |> List.sortBy (fun tbl -> tbl.Schema, tbl.Name)

    let schemas =
        let enumSchemas = db.Enums |> List.map (fun e -> e.Schema)
        let tableSchemas = filteredTables |> List.map (fun t -> t.Schema)
        enumSchemas @ tableSchemas |> List.distinct

    $$"""
// This code was generated by `{{provider.Name}}` -- v%%s{{version.InformationalVersion}}.
namespace {{cfg.Namespace}}
    """

    "open SqlHydra"
    "open SqlHydra.Query"

    versionModule cfg version

    for schema in schemas do
        $"module {backticks schema} ="

        let enums =
            db.Enums
            |> List.filter (fun e -> e.Schema = schema)
            |> List.map _.Name

        indent {
            for enum in enums do
                mkEnum db schema enum
                newLine
        }

        let tables =
            filteredTables
            |> List.filter (fun t -> t.Schema = schema)

        indent {
            for table in tables do
                mkTable cfg db table schema tableName columnName
                newLine

                if cfg.TableDeclarations then
                    let tblName = tableName { NamingContext.Table = table; Column = None }
                    $"let {backticks tblName} = table<{backticks tblName}>"
                    newLine
        }

    // If the user configures ProviderDbTypeAttributes, we know they are using SqlHydra.Query.
    if cfg.ProviderDbTypeAttributes then
        let emitter = provider.SqlEmitter
        let connectionType = provider.ProviderConnectionType

        if provider.Type = ProviderType.Npgsql then
            $"""
type QueryContextFactory =
    {{
        OpenContext: unit -> QueryContext
        OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext>
        /// Disposes the NpgsqlDataSource when the factory created it from a connection string; a no-op when the caller supplied their own.
        Dispose: unit -> unit
    }}
    interface System.IDisposable with
        member this.Dispose() = this.Dispose()
    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()
    static member Create(connectionString: string, ?sqlLogger) =
        // The factory creates this data source, so it owns and disposes it.
        let dataSource = Npgsql.NpgsqlDataSource.Create(connectionString)
        QueryContextFactory.CreateInternal(dataSource, (fun () -> dataSource.Dispose()), ?sqlLogger = sqlLogger)
    static member Create(dataSource: Npgsql.NpgsqlDataSource, ?sqlLogger) =
        // The caller supplied this data source, so the caller owns its lifetime.
        QueryContextFactory.CreateInternal(dataSource, ignore, ?sqlLogger = sqlLogger)
    static member private CreateInternal(dataSource: Npgsql.NpgsqlDataSource, dispose: unit -> unit, ?sqlLogger) =
        let emitter = {emitter}

        let createConn () : System.Data.Common.DbConnection =
            dataSource.OpenConnection()

        let openContext () =
            let conn = createConn ()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {{
                let! conn = dataSource.OpenConnectionAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }}

        {{
            OpenContext = openContext
            OpenContextAsync = openContextAsync
            Dispose = dispose
        }}
    """
        else
            $"""
type QueryContextFactory =
    {{
        OpenContext: unit -> QueryContext
        OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext>
    }}
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()
    interface System.IDisposable with
        member this.Dispose() = this.Dispose()
    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()
    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = {emitter}

        let createConn () : System.Data.Common.DbConnection =
            new {connectionType}(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {{
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }}

        {{
            OpenContext = openContext
            OpenContextAsync = openContextAsync
        }}
    """

}
